//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSColor, NSNumber, NSString;

@interface LPCaptionPresentationProperties : NSObject
{
    NSString *_text;
    NSColor *_color;
    double _textScale;
    NSNumber *_maximumNumberOfLines;
}

@property(retain, nonatomic) NSNumber *maximumNumberOfLines; // @synthesize maximumNumberOfLines=_maximumNumberOfLines;
@property(nonatomic) double textScale; // @synthesize textScale=_textScale;
@property(retain, nonatomic) NSColor *color; // @synthesize color=_color;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
- (void).cxx_destruct;
- (id)init;

@end

