//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSProcessInfo.h"

@interface NSProcessInfo (SafariCoreExtras)
@property(readonly, nonatomic) BOOL safari_systemSupportsSeparateContentBlockerStorage;
@property(readonly, nonatomic) BOOL safari_systemSupportsBookmarkDAVMoves;
- (BOOL)_systemIsSierraUpdate5AndAbove;
@property(readonly, nonatomic) BOOL safari_systemIsSierraUpdate4AndAbove;
@end

