//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class CKDialog;

@protocol PRUIDialogDelegate
- (void)userDidDismissDialog:(CKDialog *)arg1 clickedButton:(BOOL)arg2 checkboxChecked:(BOOL)arg3;
@end

