//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PassKitUI/PKPaymentPreferenceController.h>

@class NSMutableDictionary, PKPaymentPreferenceContact;

@interface PKPaymentRemoteDevicePreferenceController : PKPaymentPreferenceController
{
    PKPaymentPreferenceContact *_billingPreference;
    NSMutableDictionary *_instrumentToCardEntryMap;
    NSMutableDictionary *_instrumentToAcceptedPaymentApplicationsMap;
    NSMutableDictionary *_instrumentToUnavailablePaymentApplicationsMap;
}

@property(retain, nonatomic) NSMutableDictionary *instrumentToUnavailablePaymentApplicationsMap; // @synthesize instrumentToUnavailablePaymentApplicationsMap=_instrumentToUnavailablePaymentApplicationsMap;
@property(retain, nonatomic) NSMutableDictionary *instrumentToAcceptedPaymentApplicationsMap; // @synthesize instrumentToAcceptedPaymentApplicationsMap=_instrumentToAcceptedPaymentApplicationsMap;
@property(retain, nonatomic) NSMutableDictionary *instrumentToCardEntryMap; // @synthesize instrumentToCardEntryMap=_instrumentToCardEntryMap;
@property(retain, nonatomic) PKPaymentPreferenceContact *billingPreference; // @synthesize billingPreference=_billingPreference;
- (void).cxx_destruct;
- (BOOL)canSelectPreference:(id)arg1 atIndex:(unsigned long long)arg2;
- (BOOL)_isPaymentPassApplicationStateDeactivated:(long long)arg1;
- (id)_unavailableReasonForInstrument:(id)arg1;
- (id)cardEntriesForInstruments:(id)arg1 accepted:(BOOL)arg2;
- (void)_setupPreferences;
- (id)cardEntryForRemotePaymentInstrument:(id)arg1;
- (BOOL)shouldEnableSubItemInPreference:(id)arg1 preferenceIndex:(long long)arg2 subItemIndex:(long long)arg3;
- (id)titleForSubItemInPreference:(id)arg1 preferenceIndex:(long long)arg2 subItemIndex:(long long)arg3;
- (long long)numberOfSubItemInPreference:(id)arg1 preferenceIndex:(long long)arg2;
- (long long)numberOfMenuItemsInSection:(long long)arg1;
- (void)updatePreferences;
- (void)setModel:(id)arg1;

@end

