//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface _DKPrivacyMaintainer : NSObject
{
}

+ (void)maintainPrivacyWithKnowledgeStorage:(id)arg1 deleteMaxCount:(unsigned long long)arg2 objectMaxCount:(unsigned long long)arg3 objectMaxLifespan:(double)arg4;

@end

