//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CoreDuet/_DKSyncCompositeOperation.h>

@class NSDate, _DKSync2Policy, _DKSyncPeer, _DKSyncType;

@interface _DKPerformSyncDownPeerDeletionsOperation : _DKSyncCompositeOperation
{
    id <_DKSyncLocalKnowledgeStorage> _localStorage;
    id <_DKSyncRemoteKnowledgeStorage> _transport;
    _DKSyncPeer *_peer;
    _DKSync2Policy *_policy;
    _DKSyncType *_type;
    NSDate *_highWaterMark;
    unsigned long long _batchNumber;
}

- (void).cxx_destruct;
- (void)handleFetchedDeletedEventIDs:(id)arg1 requestDate:(id)arg2 window:(id)arg3;
- (void)performSyncDownPeerDeletionsWithPreviousWindow:(id)arg1;
- (void)performSyncDownPeerDeletionsWithHighWaterMark:(id)arg1 orError:(id)arg2;
- (void)performSyncDownPeerDeletions;
- (void)main;
- (BOOL)isAsynchronous;
- (id)initWithParent:(id)arg1 localStorage:(id)arg2 transport:(id)arg3 peer:(id)arg4 policy:(id)arg5 type:(id)arg6;

@end

