//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface _DKSyncMetadataStorage : NSObject
{
}

+ (id)lastSyncDownWindowMissingForWindows:(id)arg1 overlappingWindowMinimumDate:(id)arg2 windowMaximumDate:(id)arg3;
+ (id)eventFromFetchedWindow:(id)arg1 windowStreamName:(id)arg2 transportName:(id)arg3;
+ (id)bookmarkStreamNameWithSourceDeviceID:(id)arg1;
+ (id)windowStreamNameWithSourceDeviceID:(id)arg1;

@end

