//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSPredicate, NSString;

@interface _DKTombstoneRequirement : NSObject
{
    NSString *_identifier;
}

+ (id)requirement;
@property(readonly) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (void)assignPropertiesToTombstone:(id)arg1 extractedFromPartialEvent:(id)arg2;
- (void)assignPropertiesToTombstone:(id)arg1 extractedFromEvent:(id)arg2;
@property(readonly) NSString *propertyToFetch;
@property(readonly) NSPredicate *eventPredicate;
@property(readonly) NSPredicate *predicate;

@end

