//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableSet, NSObject<OS_dispatch_queue>;

@interface ADAdServingDaemonProxy : NSObject
{
    BOOL _serviceLaunchThrottled;
    BOOL _waitingForAdServingDaemon;
    BOOL _openApplicationInProgress;
    double _lastLaunchTimestamp;
    long long _unexpectedTerminationCount;
    long long _interruptionCount;
    double _nextScheduledLaunch;
    NSMutableSet *_launchAssertions;
    NSObject<OS_dispatch_queue> *_proxyQueue;
}

+ (id)sharedInstance;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *proxyQueue; // @synthesize proxyQueue=_proxyQueue;
@property(retain, nonatomic) NSMutableSet *launchAssertions; // @synthesize launchAssertions=_launchAssertions;
@property(nonatomic) double nextScheduledLaunch; // @synthesize nextScheduledLaunch=_nextScheduledLaunch;
@property(nonatomic) long long interruptionCount; // @synthesize interruptionCount=_interruptionCount;
@property(nonatomic) long long unexpectedTerminationCount; // @synthesize unexpectedTerminationCount=_unexpectedTerminationCount;
@property(nonatomic) double lastLaunchTimestamp; // @synthesize lastLaunchTimestamp=_lastLaunchTimestamp;
@property(nonatomic) BOOL openApplicationInProgress; // @synthesize openApplicationInProgress=_openApplicationInProgress;
@property(nonatomic) BOOL waitingForAdServingDaemon; // @synthesize waitingForAdServingDaemon=_waitingForAdServingDaemon;
@property(readonly, nonatomic) BOOL serviceLaunchThrottled; // @synthesize serviceLaunchThrottled=_serviceLaunchThrottled;
- (void)dealloc;
- (void)reportAdServingDaemonInterruption;
- (void)reportAdServingDaemonUnexpectedTermination;
- (void)_adServingDaemonAvailable;
- (void)performPostAppLaunchActions:(id)arg1;
- (void)_considerLaunchingAdServingDaemon;
- (void)considerLaunchingAdServingDaemon;
@property(readonly, nonatomic) double remainingLaunchBackoff;
- (void)resetAdServingDaemonThrottle;
- (void)releaseLaunchAssertion:(id)arg1;
- (void)takeLaunchAssertion:(id)arg1;
- (id)init;

@end

