//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSMenuItem.h"

@interface SidecarMenuItem : NSMenuItem
{
    id _appTarget;
    SEL _appAction;
}

@property SEL appAction; // @synthesize appAction=_appAction;
@property __weak id appTarget; // @synthesize appTarget=_appTarget;
- (void).cxx_destruct;
- (void)withTargetActionOverride:(CDUnknownBlockType)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

