//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SidecarRequest;

__attribute__((visibility("hidden")))
@interface SidecarModalController : NSObject
{
    SidecarRequest *_request;
}

- (void).cxx_destruct;
- (void)stop:(id)arg1;
- (long long)runModalForWindow:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)initWithRequest:(id)arg1;

@end

