//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PLAgent.h"

@class PLEntryNotificationOperatorComposition;

@interface PLMacCPUGPUAgent : PLAgent
{
    PLEntryNotificationOperatorComposition *_batteryLevelChangedNotifications;
}

+ (id)entryAggregateDefinitions;
+ (id)entryEventNoneDefinitions;
+ (id)entryEventIntervalDefinitions;
+ (id)entryEventBackwardDefinitions;
+ (id)entryEventForwardDefinitions;
+ (id)entryEventPointDefinitions;
+ (id)accountingGroupDefinitions;
+ (id)railDefinitions;
+ (id)defaults;
+ (void)load;
@property(retain) PLEntryNotificationOperatorComposition *batteryLevelChangedNotifications; // @synthesize batteryLevelChangedNotifications=_batteryLevelChangedNotifications;
- (void).cxx_destruct;
- (void)logEventNone;
- (void)logEventBackwardPStatesAndQos:(id)arg1 Qos:(id)arg2;
- (void)logEventBackwardPerCoreStats:(id)arg1;
- (void)logEventBackwardPkgStats:(id)arg1;
- (void)log;
- (void)initOperatorDependancies;
- (id)init;

@end

