//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PLAgent.h"

@class PLSemaphore, PLXPCListenerOperatorComposition;

@interface PLSleepWakeAgent : PLAgent
{
    unsigned int _rootDomainConnect;
    unsigned int _pmNotifier;
    struct IONotificationPort *_systemPowerPortRef;
    PLSemaphore *_canSleepSemaphore;
    double _apSOCBasePower;
    PLXPCListenerOperatorComposition *_wakeGestureXPCListener;
    struct __IOPMConnection *_pmConnection;
}

+ (id)entryEventBackwardDefinitions;
+ (id)entryEventForwardDefinitionPowerState;
+ (id)entryEventForwardDefinitions;
+ (id)entryEventPointDefinitionCurrentKernelWakeTime;
+ (id)entryEventPointDefinitionWakeGesture;
+ (id)entryEventPointDefinitions;
+ (id)railDefinitions;
+ (void)load;
@property struct __IOPMConnection *pmConnection; // @synthesize pmConnection=_pmConnection;
@property(retain) PLXPCListenerOperatorComposition *wakeGestureXPCListener; // @synthesize wakeGestureXPCListener=_wakeGestureXPCListener;
@property double apSOCBasePower; // @synthesize apSOCBasePower=_apSOCBasePower;
@property(retain) PLSemaphore *canSleepSemaphore; // @synthesize canSleepSemaphore=_canSleepSemaphore;
@property struct IONotificationPort *systemPowerPortRef; // @synthesize systemPowerPortRef=_systemPowerPortRef;
@property unsigned int pmNotifier; // @synthesize pmNotifier=_pmNotifier;
@property unsigned int rootDomainConnect; // @synthesize rootDomainConnect=_rootDomainConnect;
- (void).cxx_destruct;
- (void)registerForDarkwakeEvent;
- (id)wakeReasonsAsNSString;
- (id)wakeReasons;
- (void)logWakeEntries:(id)arg1 withCurrentTime:(unsigned long long)arg2 withIsDarkwake:(_Bool)arg3 withCapabilities:(unsigned int)arg4;
- (void)logSleepEntries:(id)arg1;
- (void)systemPoweredOn:(_Bool)arg1 withCapabilities:(unsigned int)arg2;
- (void)systemPoweredOn:(_Bool)arg1;
- (void)logEventPointWakeGesture:(id)arg1;
- (void)log;
- (void)initOperatorDependancies;
- (id)init;

@end

