//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PLAgent.h"

@class PLEntryNotificationOperatorComposition;

@interface PLSMCAgent : PLAgent
{
    PLEntryNotificationOperatorComposition *_sbc;
}

+ (id)entryAggregateDefinitions;
+ (id)entryEventNoneDefinitions;
+ (id)entryEventIntervalDefinitions;
+ (id)entryEventBackwardDefinitionAccumulatedKeys;
+ (id)entryEventBackwardDefinitions;
+ (id)entryEventForwardDefinitions;
+ (id)entryEventPointDefinitionThermalKeys;
+ (id)entryEventPointDefinitions;
+ (void)load;
@property(retain) PLEntryNotificationOperatorComposition *sbc; // @synthesize sbc=_sbc;
- (void).cxx_destruct;
- (id)configKeys;
- (id)accumulatedKeys;
- (id)thermalKeys;
- (id)keyBlacklist;
- (BOOL)isBlacklisted:(id)arg1;
- (id)readKeyAsNumeric:(id)arg1;
- (CDStruct_3d4409aa *)smcConnection;
- (BOOL)accumSupported;
- (void)logEventPointThermalKeys;
- (void)log;
- (void)initOperatorDependancies;
- (id)init;

@end

