//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ROCKImpersonateable.h"

@class NSData;

@protocol UHAHidManagerInterposingInterface <ROCKImpersonateable>
@property(readonly) BOOL forceClickPerformsQuickLook;
- (void)registerServiceId:(unsigned long long)arg1 dataHandler:(void (^)(NSData *))arg2;
- (NSData *)pullNextEventDataFromQueue;
- (void)registerEventPingHandler:(void (^)(void))arg1;
@end

