//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ROCKForwardingInterposer.h"

#import "UHAHidManagerInterface.h"

@class NSString;

@interface UHAHidManagerInterposer : ROCKForwardingInterposer <UHAHidManagerInterface>
{
    id <UHAHidSettingsInterface> settings;
}

- (void)endKeyFocusForScene:(id)arg1 contextId:(unsigned int)arg2;
- (void)beginKeyFocusForScene:(id)arg1 contextId:(unsigned int)arg2;
@property(readonly) BOOL forceClickPerformsQuickLook;
- (void)registerServiceId:(unsigned long long)arg1 handler:(CDUnknownBlockType)arg2;
- (struct __IOHIDEvent *)pullNextEventFromQueue;
- (void)registerEventPingHandler:(CDUnknownBlockType)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

