//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ROCKImpersonateable.h"

@protocol UHAMenuControllerInterface <ROCKImpersonateable>
@property(copy, nonatomic) CDUnknownBlockType contextMenuDidClose;
@property(copy, nonatomic) CDUnknownBlockType performItemAction;
@property(copy, nonatomic) CDUnknownBlockType validateItem;
- (void)showContextMenu:(id <UHAMenuInterface>)arg1 atLocation:(struct CGPoint)arg2;
- (void)rebuildMenu:(id <UHAMenuInterface>)arg1;
- (void)setMainMenuBar:(id <UHAMenuInterface>)arg1;
@end

