//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ROCKImpersonateable.h"

@class NSArray;

@protocol UHATouchBarControllerInterface <ROCKImpersonateable>
@property(copy, nonatomic) CDUnknownBlockType creationHandler;
- (void)setTouchBarDescriptions:(NSArray *)arg1;
@end

