//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <RemoteManagement/RMUserNotificationContext.h>

@class NSString;

@interface RMAppLimitWarningUserNotificationContext : RMUserNotificationContext
{
}

- (id)localizedUserNotificationBodyKey;
- (id)localizedUserNotificationTitleKey;
@property(copy, nonatomic) NSString *limitDisplayName;
- (id)initWithIdentifier:(id)arg1;

@end

