//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class RMAskForTimeRequest;

@protocol RMAskForTimeInterface <NSObject>
- (void)isRestrictionsPasscodeSet:(void (^)(BOOL))arg1;
- (void)shouldRequestMoreTime:(void (^)(BOOL, NSError *))arg1;
- (void)fetchAskForTimeFromMeWithCompletionHandler:(void (^)(NSArray *, NSDictionary *, NSError *))arg1;
- (void)sendAskForTimeRequest:(RMAskForTimeRequest *)arg1 completionHandler:(void (^)(NSError *))arg2;
@end

