//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <RemoteManagement/RMUserNotificationContext.h>

@interface RMAskForTimeRequestReceivedUserNotificationContext : RMUserNotificationContext
{
}

+ (id)supportedCategories;
- (id)categoryIdentifier;
- (id)localizedUserNotificationBodyKey;
- (id)localizedUserNotificationTitleKey;
- (id)initWithAskForTimeRequestIdentifier:(id)arg1 childName:(id)arg2 requestedResourceName:(id)arg3;

@end

