//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <RemoteManagement/RMUserNotificationContext.h>

@interface RMDeviceDowntimeUserNotificationContext : RMUserNotificationContext
{
    BOOL _downtimeEnabled;
}

@property(nonatomic) BOOL downtimeEnabled; // @synthesize downtimeEnabled=_downtimeEnabled;
- (id)categoryIdentifier;
- (id)localizedUserNotificationBodyKey;
- (id)localizedUserNotificationTitleKey;
- (id)init;

@end

