//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <RemoteManagement/RMUserNotificationContext.h>

@class NSString;

@interface RMDeviceDowntimeUserNotificationContext : RMUserNotificationContext
{
}

+ (BOOL)supportsSecureCoding;
- (id)destinations;
- (void)customizeNotificationContent:(id)arg1 withCompletionBlock:(CDUnknownBlockType)arg2;
- (void)setEndDateComponents:(id)arg1;
- (id)init;

@end

