//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <RemoteManagement/RMCoreOrganizationSettings.h>

@class RMFamilyOrganization;

@interface RMFamilyOrganizationSettings : RMCoreOrganizationSettings
{
}


// Remaining properties
@property(nonatomic) BOOL canManageOthers; // @dynamic canManageOthers;
@property(nonatomic) BOOL canManageSelf; // @dynamic canManageSelf;
@property(nonatomic) BOOL isManaged; // @dynamic isManaged;
@property(retain, nonatomic) RMFamilyOrganization *organization; // @dynamic organization;
@end

