//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

@class RMFamilyOrganizationSettings;

@interface RMFamilyOrganization : NSManagedObject
{
}

+ (id)fetchOrCreateFamilyOrganizationWithContext:(id)arg1 error:(id *)arg2;

// Remaining properties
@property(retain, nonatomic) RMFamilyOrganizationSettings *settings; // @dynamic settings;

@end

