//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class RMAskForTimeClient;

@interface RMManagementState : NSObject
{
    RMAskForTimeClient *_askForTimeClient;
}

@property(readonly, nonatomic) RMAskForTimeClient *askForTimeClient; // @synthesize askForTimeClient=_askForTimeClient;
- (void).cxx_destruct;
- (void)shouldRequestMoreTime:(CDUnknownBlockType)arg1;
- (void)isRestrictionsPasscodeSet:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) BOOL shouldRequestMoreTime;
@property(readonly, nonatomic) BOOL isRestrictionsPasscodeSet;
- (id)init;

@end

