//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol RMManagementStateServerInterface <NSObject>
- (void)isRestrictionsPasscodeSetWithCompletionHandler:(void (^)(BOOL, NSError *))arg1;
- (void)shouldRequestMoreTimeWithCompletionHandler:(void (^)(BOOL, NSError *))arg1;
- (void)screenTimeSyncStateWithCompletionHandler:(void (^)(long long, NSError *))arg1;
- (void)setScreenTimeEnabled:(BOOL)arg1 completionHandler:(void (^)(NSError *))arg2;
- (void)screenTimeStateWithCompletionHandler:(void (^)(long long, NSError *))arg1;
@end

