//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSPersistentHistoryToken, NSPersistentStore, NSPersistentStoreCoordinator;

@interface RMMigrator : NSObject
{
    NSPersistentStoreCoordinator *_coordinator;
    NSPersistentStore *_localStore;
    NSPersistentStore *_cloudStore;
    NSPersistentHistoryToken *_migratedToken;
}

- (void).cxx_destruct;
- (BOOL)addHistoryToken:(id)arg1 forAuthor:(id)arg2 toMetadataForStore:(id)arg3 error:(id *)arg4;
- (id)historyTokenForAuthor:(id)arg1 fromStore:(id)arg2;
- (BOOL)isChangeInteresting:(id)arg1;
- (BOOL)_checkPreconditionsError:(id *)arg1;
- (BOOL)migrateToCloud:(id *)arg1;
- (BOOL)migrateToLocal:(id *)arg1;
- (id)initWithPersistentStoreCoordinator:(id)arg1;

@end

