//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CATOperation.h"

@class NSPersistentHistoryToken, NSPersistentStore, NSString;

@interface RMPersistenceStoreChangeProcessingOperation : CATOperation
{
    NSPersistentHistoryToken *_token;
    NSPersistentStore *_store;
    NSString *_storeIdentifier;
    id <RMPersistenceStoreChangeProcessingOperationDelegate> _delegate;
}

@property(nonatomic) __weak id <RMPersistenceStoreChangeProcessingOperationDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSString *storeIdentifier; // @synthesize storeIdentifier=_storeIdentifier;
@property(retain, nonatomic) NSPersistentStore *store; // @synthesize store=_store;
@property(retain, nonatomic) NSPersistentHistoryToken *token; // @synthesize token=_token;
- (void).cxx_destruct;
- (id)_transactionsAfterToken:(id)arg1 store:(id)arg2 context:(id)arg3;
- (void)main;
- (BOOL)isAsynchronous;
- (id)initWithStore:(id)arg1 storeIdentifier:(id)arg2 token:(id)arg3;

@end

