//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber, NSString;

@interface FTPNRSubscription : NSObject
{
    NSString *_phoneNumber;
    NSString *_ICCID;
    NSNumber *_subscriptionNumber;
    BOOL _isInitialized;
}

@property(readonly) BOOL isInitialized; // @synthesize isInitialized=_isInitialized;
@property(readonly) NSNumber *subscriptionNumber; // @synthesize subscriptionNumber=_subscriptionNumber;
@property(readonly) NSString *ICCID; // @synthesize ICCID=_ICCID;
@property(readonly) NSString *phoneNumber; // @synthesize phoneNumber=_phoneNumber;
- (void).cxx_destruct;
- (id)description;
- (id)initWithPhoneNumber:(id)arg1 ICCID:(id)arg2 subscriptionNumber:(id)arg3 isInitialized:(BOOL)arg4;

@end

