//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FTSelectedPNRSubscription : NSObject
{
}

- (id)_legacy_carrierBundleValueForKey:(id)arg1 ofType:(Class)arg2;
- (id)selectedPhoneNumberRegistrationRegistrationCarrierBundleValueForKey:(id)arg1 ofType:(Class)arg2 withFallbackValue:(id)arg3;
- (id)selectedRegistrationPhoneNumberWithError:(id *)arg1;
- (BOOL)isSelectedPhoneNumberRegistrationSubscriptionContext:(id)arg1;
- (id)selectedPhoneNumberRegistrationSubscriptionWithError:(id *)arg1;
- (BOOL)_userSelectionDoesMatchSubscriptionNumber:(long long)arg1;

@end

