//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FTSelectedPNRSubscription : NSObject
{
}

+ (id)subscriptionFromAvailableSubscriptions:(id)arg1 matchingSelectedSubscription:(id)arg2;
+ (BOOL)isPhoneNumber:(id)arg1 equivalentToExistingPhoneNumber:(id)arg2;
- (id)_legacy_carrierBundleValueForKey:(id)arg1 ofType:(Class)arg2;
- (id)selectedPhoneNumberRegistrationRegistrationCarrierBundleValueForKey:(id)arg1 ofType:(Class)arg2 withFallbackValue:(id)arg3;
- (id)_reevaluateCachedSelectedPhoneNumberWithContext:(id)arg1 error:(id *)arg2;
- (id)_reevaluateCachedSelectedPhoneNumberRegistrationWithSubscription:(id)arg1 activeContexts:(id)arg2 fallbackProhibited:(BOOL)arg3 persistUpdate:(BOOL)arg4 error:(id *)arg5;
- (id)_firstPresentSubscriptionFromAvailableSubscriptions:(id)arg1;
- (id)_subscriptionFromAvailableSubscriptions:(id)arg1 matchingSelectedLabel:(id)arg2;
- (void)_reevaluateDualIdentityModeWithSubscriptionInfo:(id)arg1;
- (BOOL)_doesSubscriptionInfoContainMultipleUniqueLabels:(id)arg1;
- (BOOL)_doesSubscriptionInfoContainMultipleLabels:(id)arg1;
- (id)_reevaluateCachedActiveSubscriptionWithError:(id *)arg1;
- (id)_reevaluateCachedSubscriptionWithError:(id *)arg1;
- (BOOL)_isIdentityFallbackProhibitedForDeviceBasedOnCapability:(long long)arg1 subscriptionInfo:(id)arg2;
- (BOOL)_isInDualPhoneIdentityModeBasedOnCapability:(long long)arg1;
- (BOOL)isDeviceInDualPhoneIdentityMode;
- (id)setSelectedPhoneNumberRegistrationSubscriptionNumber:(id)arg1;
- (id)selectedRegistrationPhoneNumberWithError:(id *)arg1;
- (BOOL)isSelectedPhoneNumberRegistrationSubscriptionContext:(id)arg1;
- (id)selectedPhoneNumberRegistrationSubscriptionWithError:(id *)arg1 persistUpdateIfNeeded:(BOOL)arg2;
- (void)reevaluateAndPersistSelectedPhoneNumberRegistrationSubscription;
- (id)selectedPhoneNumberRegistrationSubscriptionWithError:(id *)arg1;
- (id)_PNRSubscriptionFromCTSubscriptionContext:(id)arg1;
- (void)_makeSubscriptionChoiceStickyBasedOnPreviousReference:(id)arg1 newSelection:(id)arg2;
- (id)_userSelectedReferencePNRSubscription;
- (BOOL)_PNRSubscription:(id)arg1 doesMatchSubscriptionNumber:(long long)arg2;

@end

