//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <TimeSync/TSgPTPNetworkPort.h>

@class TSgPTPPortStatistics;

@interface TSgPTPFDPtPPort : TSgPTPNetworkPort
{
}

+ (id)diagnosticDescriptionForService:(unsigned int)arg1 withIndent:(id)arg2;
@property(readonly, nonatomic) BOOL remotePDelayLogMeanInterval; // @dynamic remotePDelayLogMeanInterval;
@property(readonly, nonatomic) BOOL localPDelayLogMeanInterval; // @dynamic localPDelayLogMeanInterval;
@property(readonly, nonatomic) TSgPTPPortStatistics *statistics; // @dynamic statistics;

@end

