//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <HMFoundation/HMFSystemInfo.h>

@interface HMFSystemInfo_osx : HMFSystemInfo
{
    struct __SCDynamicStore *_hostNameNotificationDynamicStore;
}

@property(nonatomic) struct __SCDynamicStore *hostNameNotificationDynamicStore; // @synthesize hostNameNotificationDynamicStore=_hostNameNotificationDynamicStore;
- (void)startMonitoringSystemChanges;
- (void)updateName;
- (void)sethostNameNotificationDynamicStore:(struct __SCDynamicStore *)arg1;
- (void)dealloc;
- (void)__initialize;

@end

