//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface AMSDevice : NSObject
{
}

+ (id)_systemVersionDictionary;
+ (id)_dataForNVRAMKey:(id)arg1;
+ (id)_compatibleProductType;
+ (BOOL)deviceIsSeedBuild;
+ (BOOL)deviceIsiPod;
+ (BOOL)deviceIsiPhone;
+ (BOOL)deviceIsiPad;
+ (BOOL)deviceIsInternalBuild;
+ (BOOL)deviceIsAppleWatch;
+ (BOOL)deviceIsAppleTV;
+ (BOOL)deviceIsAudioAccessory;
+ (id)uniqueDeviceId;
+ (id)thinnedAppVariantId;
+ (id)serialNumber;
+ (id)screenScale;
+ (id)productVersion;
+ (id)productType;
+ (id)MLBSerialNumber;
+ (id)macAddressData;
+ (id)macAddress;
+ (id)localIPAddress;
+ (BOOL)isRunningInStoreDemoMode;
+ (id)hardwarePlatform;
+ (id)deviceGUID;
+ (id)buildVersion;
+ (id)deviceOffersForProductType:(unsigned long long)arg1;
+ (BOOL)deviceOffersContainProductType:(unsigned long long)arg1;
+ (id)_followUpItemWithIdentifier:(id)arg1 account:(id)arg2 priority:(long long)arg3 logKey:(id)arg4;
+ (void)registerCompanionWithSerialNumber:(id)arg1;
+ (BOOL)shouldPresentSetupOffersForAccount:(id)arg1;
+ (BOOL)postFollowUpForDeviceOffersWithIdentitier:(id)arg1 account:(id)arg2 priority:(long long)arg3 logKey:(id)arg4;
+ (id)deviceOffersForType:(unsigned long long)arg1;
+ (BOOL)deviceOffersContainType:(unsigned long long)arg1;
+ (BOOL)clearFollowUpForDeviceOffersWithIdentifier:(id)arg1 account:(id)arg2;
+ (BOOL)isGift;
+ (BOOL)isEligibleForOffers;
+ (BOOL)expressedIntent;
+ (id)deviceOffers;

@end

