//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber, NSString;

@interface AMSDeviceOffer : NSObject
{
    BOOL _downgrading;
    BOOL _subscribed;
    NSNumber *_adamId;
    NSString *_description;
    NSString *_offerIdentifier;
    unsigned long long _productType;
}

@property unsigned long long productType; // @synthesize productType=_productType;
@property(getter=isSubscribed) BOOL subscribed; // @synthesize subscribed=_subscribed;
@property(copy) NSString *offerIdentifier; // @synthesize offerIdentifier=_offerIdentifier;
@property(getter=isDowngrading) BOOL downgrading; // @synthesize downgrading=_downgrading;
@property(copy) NSString *description; // @synthesize description=_description;
@property(copy) NSNumber *adamId; // @synthesize adamId=_adamId;
- (void).cxx_destruct;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;
@property(readonly) unsigned long long offerType;
- (id)initWithDictionary:(id)arg1;
- (id)initWithAdamId:(id)arg1;

@end

