//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AppleMediaServices/AMSTask.h>

@class NSString;

@interface AMSFamilyInfoLookupTask : AMSTask
{
    id <AMSFamilyInfoLookupBagContract> _bagContract;
    NSString *_logKey;
}

@property(retain) NSString *logKey; // @synthesize logKey=_logKey;
@property(retain) id <AMSFamilyInfoLookupBagContract> bagContract; // @synthesize bagContract=_bagContract;
- (void).cxx_destruct;
- (id)_processURLResult:(id)arg1;
- (id)performFamilyInfoLookup;
- (id)initWithBagContract:(id)arg1;

@end

