//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AMSRemoteNotificationParsable.h"
#import "AMSUserNotificationIntentCallback.h"

__attribute__((visibility("hidden")))
@interface AMSRemoteNotificationFollowUp : NSObject <AMSRemoteNotificationParsable, AMSUserNotificationIntentCallback>
{
}

+ (id)_sharedNotificationCenter;
+ (id)_generateNotificationFromPayload:(id)arg1;
+ (id)_followUpActionFromActionDictionary:(id)arg1 logKey:(id)arg2;
+ (BOOL)_shouldClearFollowUpFromPayload:(id)arg1;
+ (BOOL)_shouldAllowFollowUp:(id)arg1;
+ (void)_performPostWithPayload:(id)arg1;
+ (void)_performClearWithPayload:(id)arg1;
+ (void)userNotification:(id)arg1 selectedButtonAction:(id)arg2;
+ (long long)supportedActionType;
+ (void)handleNotificationPayload:(id)arg1;

@end

