//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AMSURLProtocolDialogHandling.h"

@class AMSURLTaskInfo, NSArray, NSDictionary, NSString, NSURL;

__attribute__((visibility("hidden")))
@interface AMSURLProtocolDialog : NSObject <AMSURLProtocolDialogHandling>
{
    NSDictionary *_dialogDictionary;
    NSURL *_redirectURL;
    AMSURLTaskInfo *_taskInfo;
    NSString *_logKey;
}

@property(retain) NSString *logKey; // @synthesize logKey=_logKey;
@property(readonly) AMSURLTaskInfo *taskInfo; // @synthesize taskInfo=_taskInfo;
@property(readonly) NSDictionary *dialogDictionary; // @synthesize dialogDictionary=_dialogDictionary;
- (void).cxx_destruct;
@property(readonly) NSString *message;
@property(readonly) NSArray *buttons;
@property(readonly) NSString *title;
- (id)runDialog;
- (id)initWithDialogDictionary:(id)arg1 taskInfo:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

