//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTextView.h"

@interface CalUITextFieldEditor : NSTextView
{
    BOOL _shouldAllowVibrancy;
    id <CalUITextFieldEditorDelegate> _calUITextFieldDelegate;
}

@property BOOL shouldAllowVibrancy; // @synthesize shouldAllowVibrancy=_shouldAllowVibrancy;
@property __weak id <CalUITextFieldEditorDelegate> calUITextFieldDelegate; // @synthesize calUITextFieldDelegate=_calUITextFieldDelegate;
- (void).cxx_destruct;
- (BOOL)isRichText;
- (BOOL)readSelectionFromPasteboard:(id)arg1;
- (BOOL)allowsVibrancy;
- (id)readablePasteboardTypes;
- (void)selectAll:(id)arg1;
- (void)keyDown:(id)arg1;
- (void)mouseDown:(id)arg1;

@end

