//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol STYWakeDataProvider <NSObject>
@property __weak id <STYWakeDataConsumer> consumer;
- (unsigned long long)sleepType;
- (unsigned long long)firstHidWakeEventAfter:(unsigned long long)arg1 before:(unsigned long long)arg2;
- (double)lastWakeTime:(double *)arg1;
@end

