//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MDSearchableIndexService, NSString;

@interface CSIndexClientConnection : NSObject
{
    BOOL _internal;
    BOOL _searchInternal;
    BOOL _quotaDisabled;
    BOOL _isExtension;
    int _pid;
    unsigned int _euid;
    unsigned int _egid;
    NSString *_protectionClass;
    NSString *_bundleID;
    MDSearchableIndexService *_service;
}

@property(readonly, nonatomic) MDSearchableIndexService *service; // @synthesize service=_service;
@property(readonly, nonatomic) BOOL isExtension; // @synthesize isExtension=_isExtension;
@property(readonly, nonatomic) BOOL quotaDisabled; // @synthesize quotaDisabled=_quotaDisabled;
@property(readonly, nonatomic) BOOL searchInternal; // @synthesize searchInternal=_searchInternal;
@property(readonly, nonatomic) BOOL internal; // @synthesize internal=_internal;
@property(readonly, nonatomic) unsigned int egid; // @synthesize egid=_egid;
@property(readonly, nonatomic) unsigned int euid; // @synthesize euid=_euid;
@property(readonly, nonatomic) int pid; // @synthesize pid=_pid;
@property(readonly, nonatomic) NSString *bundleID; // @synthesize bundleID=_bundleID;
@property(readonly, nonatomic) NSString *protectionClass; // @synthesize protectionClass=_protectionClass;
- (void).cxx_destruct;
- (id)initWithConnection:(id)arg1 indexer:(id)arg2;

@end

