//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSMutableOrderedSet, NSString;

@interface CSSearchClientConnection : NSObject
{
    BOOL _searchInternal;
    BOOL _isExtension;
    unsigned int _outBatchCount;
    int _pid;
    unsigned int _euid;
    unsigned int _egid;
    NSMutableDictionary *_queryTasks;
    NSMutableOrderedSet *_pausedTasks;
    NSString *_protectionClass;
    NSString *_bundleID;
}

@property(readonly, nonatomic) BOOL isExtension; // @synthesize isExtension=_isExtension;
@property(readonly, nonatomic) BOOL searchInternal; // @synthesize searchInternal=_searchInternal;
@property(readonly, nonatomic) unsigned int egid; // @synthesize egid=_egid;
@property(readonly, nonatomic) unsigned int euid; // @synthesize euid=_euid;
@property(readonly, nonatomic) int pid; // @synthesize pid=_pid;
@property(readonly, nonatomic) NSString *bundleID; // @synthesize bundleID=_bundleID;
@property(readonly, nonatomic) NSString *protectionClass; // @synthesize protectionClass=_protectionClass;
@property(retain, nonatomic) NSMutableOrderedSet *pausedTasks; // @synthesize pausedTasks=_pausedTasks;
@property(retain, nonatomic) NSMutableDictionary *queryTasks; // @synthesize queryTasks=_queryTasks;
@property(readonly, nonatomic) unsigned int outBatchCount; // @synthesize outBatchCount=_outBatchCount;
- (void).cxx_destruct;
- (void)_didReceiveResultsBatchCompletion;
- (void)_willSendResultsBatch:(id)arg1 qid:(long long)arg2;
- (void)dealloc;
- (void)cancelQueryTasks;
- (void)setQueryTask:(id)arg1 forQueryID:(long long)arg2;
- (id)queryTask:(long long)arg1;
- (void)cancelQueryTask:(long long)arg1;
- (id)initWithConnection:(id)arg1;

@end

