//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IDSCurrentServerTimePair : NSObject
{
    unsigned long long _initialProcessTime;
    unsigned long long _initialServerTimeInNanoSeconds;
}

@property(readonly, nonatomic) unsigned long long initialServerTimeInNanoSeconds; // @synthesize initialServerTimeInNanoSeconds=_initialServerTimeInNanoSeconds;
@property(readonly, nonatomic) unsigned long long initialProcessTime; // @synthesize initialProcessTime=_initialProcessTime;
- (id)initWithInitialProcessTime:(unsigned long long)arg1 initialServerTimeInNanoSeconds:(unsigned long long)arg2;

@end

