//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSData, NSDate, NSDictionary, NSString, NSUUID;

@interface IDSGroupSessionParticipantUpdate : NSObject
{
    NSUUID *_groupUUID;
    unsigned long long _participantIdentifier;
    NSString *_participantDestinationID;
    unsigned long long _participantUpdateType;
    BOOL _fromServer;
    NSDate *_serverDate;
    NSData *_participantData;
    NSData *_clientContextData;
    NSArray *_members;
    NSDictionary *_participantIDs;
    NSUUID *_relaySessionID;
}

@property(readonly, nonatomic) NSArray *members; // @synthesize members=_members;
@property(readonly, nonatomic) NSDate *serverDate; // @synthesize serverDate=_serverDate;
@property(readonly, nonatomic) BOOL fromServer; // @synthesize fromServer=_fromServer;
@property(readonly, nonatomic) NSUUID *relaySessionID; // @synthesize relaySessionID=_relaySessionID;
@property(readonly, nonatomic) NSDictionary *participantIDs; // @synthesize participantIDs=_participantIDs;
@property(readonly, nonatomic) NSData *clientContextData; // @synthesize clientContextData=_clientContextData;
@property(readonly, nonatomic) NSData *participantData; // @synthesize participantData=_participantData;
@property(readonly, nonatomic) unsigned long long participantUpdateType; // @synthesize participantUpdateType=_participantUpdateType;
@property(readonly, nonatomic) NSString *participantDestinationID; // @synthesize participantDestinationID=_participantDestinationID;
@property(readonly, nonatomic) unsigned long long participantIdentifier; // @synthesize participantIdentifier=_participantIdentifier;
@property(readonly, nonatomic) NSUUID *groupUUID; // @synthesize groupUUID=_groupUUID;
- (void).cxx_destruct;
- (id)debugDescription;
- (id)description;
- (id)dictionaryRepresentation;
- (id)initWithDictionaryRepresentation:(id)arg1;
- (id)initWithGroupUUID:(id)arg1 participantIdentifier:(unsigned long long)arg2 participantDestinationID:(id)arg3 participantUpdateType:(unsigned long long)arg4 fromServer:(BOOL)arg5 serverDate:(id)arg6 participantData:(id)arg7 clientContextData:(id)arg8 members:(id)arg9 participantIDs:(id)arg10 relaySessionID:(id)arg11;

@end

