//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CNAutocompleteQueryCacheMissAuditor, CNCache, CNObservable;

@interface CNAutocompleteQueryCacheHelper : NSObject
{
    CNCache *_cache;
    CNObservable *_fallbackObservable;
    CNAutocompleteQueryCacheMissAuditor *_cacheMissAuditor;
    id <CNSchedulerProvider> _schedulerProvider;
}

+ (BOOL)shouldCacheResults:(id)arg1;
+ (id)stringByRemovingLastCharacterFromString:(id)arg1;
+ (id)cache_os_log;
@property(readonly, nonatomic) id <CNSchedulerProvider> schedulerProvider; // @synthesize schedulerProvider=_schedulerProvider;
@property(readonly, nonatomic) CNAutocompleteQueryCacheMissAuditor *cacheMissAuditor; // @synthesize cacheMissAuditor=_cacheMissAuditor;
@property(readonly, nonatomic) CNObservable *fallbackObservable; // @synthesize fallbackObservable=_fallbackObservable;
@property(readonly, nonatomic) CNCache *cache; // @synthesize cache=_cache;
- (void).cxx_destruct;
- (id)observablesForSearchString:(id)arg1 withCachedResults:(id)arg2;
- (id)observablesForSearchString:(id)arg1 andCompletePromise:(id)arg2;
- (id)observableForSearchString:(id)arg1;
- (id)initWithCache:(id)arg1 fallbackObservable:(id)arg2 cacheMissAuditor:(id)arg3 schedulerProvider:(id)arg4;
- (id)initWithCache:(id)arg1 fallbackObservable:(id)arg2;

@end

