//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <FinderKit/FI_IPropertyValueController.h>

@class FI_TDesktopTitleBubbleView;

__attribute__((visibility("hidden")))
@interface FI_TPropertyTitleBubbleViewController : FI_IPropertyValueController
{
    struct TNSRef<NSDictionary, void> _titleAttributes;
    unsigned long long _textAlignment;
}

+ (id)keyPathsForValuesAffectingShouldBeVisible;
@property(nonatomic) unsigned long long textAlignment; // @synthesize textAlignment=_textAlignment;
- (id).cxx_construct;
- (void).cxx_destruct;
- (_Bool)shouldBeVisible;
- (id)font;
- (void)setValue:(id)arg1;
- (id)titleAttributes;
@property(readonly, retain, nonatomic) FI_TDesktopTitleBubbleView *titleView;
- (void)viewLoaded;
- (void)initCommon;

@end

