//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "QLPreviewItem.h"

@class NSString, NSURL;

__attribute__((visibility("hidden")))
@interface FI_TQLMultiPreviewItem : NSObject <QLPreviewItem>
{
    struct TFENodeVector _nodes;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)previewItemDisplayName;
@property(readonly) NSString *previewItemTitle;
- (id)launchURL;
@property(readonly) NSURL *previewItemURL;
- (struct TString)urlString;
@property(readonly, nonatomic) const struct TFENodeVector *nodes; // @dynamic nodes;
- (BOOL)isEqual:(id)arg1;
- (id)init;
- (id)initWithNodes:(const struct TFENodeVector *)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) id previewItemDisplayState;
@property(readonly) Class superclass;

@end

