//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <FinderKit/FI_TViewController.h>

@class NSArray;

__attribute__((visibility("hidden")))
@interface FI_TBaseInfoWindowViewController : FI_TViewController
{
    struct TFENodeVector _targetNodes;
    struct TNSRef<NSArray<IPropertyValueControllers *>, void> _valueControllers;
    struct TRef<NSObject<OS_dispatch_queue>*, TRetainReleasePolicy<dispatch_queue_t>> _prefetchValuesQueue;
}

+ (id)controller;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)nodeMDAttributeChanged:(const struct TFENode *)arg1 attributes:(id)arg2 isDisplayAttributes:(_Bool)arg3;
- (void)nodesGoingAway:(const struct TFENodeVector *)arg1;
- (void)bulkNodesDeleted:(const struct TCoalescedNodesAddedMap *)arg1;
- (_Bool)performCmd:(SEL)arg1 forSender:(id)arg2;
- (_Bool)validateCmd:(SEL)arg1 forSender:(id)arg2;
- (void)bulkNodesChanged:(const struct TCoalescedNodesChangedMap *)arg1;
- (unsigned int)notificationOptionsForNodes:(const struct TFENodeVector *)arg1;
- (void)refresh;
- (void)prefetchValues:(const struct TFENodeVector *)arg1;
- (void)targetNodesChanged;
- (void)targetNodesChanging;
- (void)setTargetNodes:(const struct TFENodeVector *)arg1;
- (const struct TFENodeVector *)targetNodes;
@property(retain, nonatomic) NSArray *valueControllers; // @dynamic valueControllers;
- (void)loadValueControllers;
- (void)aboutToTearDown;
- (void)viewLoaded;

@end

