//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <FinderKit/FI_IBasePropertyColumnPreviewIconController.h>

__attribute__((visibility("hidden")))
@interface FI_TPropertyColumnPreviewSmallIconController : FI_IBasePropertyColumnPreviewIconController
{
    _Bool _showSmallThumbnail;
}

+ (id)keyPathsForValuesAffectingShouldBeVisible;
@property(nonatomic) _Bool showSmallThumbnail; // @synthesize showSmallThumbnail=_showSmallThumbnail;
- (_Bool)shouldBeVisible;
- (_Bool)isApplicableToNodes:(const struct TFENodeVector *)arg1;

@end

