//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <FinderKit/FI_TUpdateLayerView.h>

#import "QLPreviewCustomView.h"
#import "TMarkTornDown.h"

@class FI_TPropertyColumnPreviewLargeIconController, NSString;

__attribute__((visibility("hidden")))
@interface FI_TQLMultiPreviewView : FI_TUpdateLayerView <QLPreviewCustomView, TMarkTornDown>
{
    FI_TPropertyColumnPreviewLargeIconController *_iconController;
    _Bool _iconControllerNeedsRelease;
    struct TNSRef<FI_TQLMultiPreviewItem, void> _previewItem;
    _Bool _isTornDown;
}

+ (id)keyPathsForValuesAffectingIsLoaded;
+ (id)qlMultiPreviewView:(const struct CGRect *)arg1;
@property(readonly, getter=isTornDown) _Bool tornDown; // @synthesize tornDown=_isTornDown;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)didHide;
- (void)willHide;
- (void)close;
@property(readonly) BOOL isLoaded;
- (void)flushCachedMultiIcon;
@property(retain) id <QLPreviewItem> previewItem; // @dynamic previewItem;
@property(readonly, retain) FI_TPropertyColumnPreviewLargeIconController *iconController; // @dynamic iconController;
- (void)aboutToTearDown;
- (void)configureThumbnailer:(double)arg1 andScaleFactor:(double)arg2;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

