//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <HomeKitDaemon/HMDTLVBase.h>

#import "HMDTLVCreateParse.h"
#import "NSSecureCoding.h"

@class HMDDataStreamTransportProtocol;

@interface HMDDataStreamTransportConfiguration : HMDTLVBase <HMDTLVCreateParse, NSSecureCoding>
{
    HMDDataStreamTransportProtocol *_protocol;
}

+ (BOOL)supportsSecureCoding;
@property(readonly, copy, nonatomic) HMDDataStreamTransportProtocol *protocol; // @synthesize protocol=_protocol;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)description:(id)arg1 indent:(id)arg2;
- (id)tlvData;
- (BOOL)_parseFromTLVData;
- (id)initWithProtocol:(id)arg1;

@end

