//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <HomeKitDaemon/HMDTLVBase.h>

#import "HMDTLVCreateParse.h"
#import "NSSecureCoding.h"

@class NSArray;

@interface HMDDataStreamTransportSupportedConfiguration : HMDTLVBase <HMDTLVCreateParse, NSSecureCoding>
{
    NSArray *_configurations;
}

+ (BOOL)supportsSecureCoding;
@property(readonly, copy, nonatomic) NSArray *configurations; // @synthesize configurations=_configurations;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)description:(id)arg1 indent:(id)arg2;
- (id)tlvData;
- (BOOL)_parseFromTLVData;
- (id)initWithConfigurations:(id)arg1;

@end

