//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSError;

@protocol HMDDataStreamProtocol <NSObject>
- (BOOL)dataStream:(id <HMDDataStreamProtocolDelegate>)arg1 didReceiveMessage:(NSDictionary *)arg2;
- (void)dataStream:(id <HMDDataStreamProtocolDelegate>)arg1 didFailWithError:(NSError *)arg2;
- (void)dataStreamDidClose:(id <HMDDataStreamProtocolDelegate>)arg1;
- (void)dataStreamDidOpen:(id <HMDDataStreamProtocolDelegate>)arg1;
@end

