//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "HMFLogging.h"

@class HAPSecuritySessionEncryption, NSPointerArray, NSString;

@interface HMDDataStream : NSObject <HMFLogging>
{
    id <HMDDataStreamDelegate> _delegate;
    id <HMDDataStreamTransport> _transport;
    HAPSecuritySessionEncryption *_sessionEncryption;
    NSPointerArray *_protocols;
}

+ (id)logCategory;
@property(retain, nonatomic) NSPointerArray *protocols; // @synthesize protocols=_protocols;
@property(retain, nonatomic) HAPSecuritySessionEncryption *sessionEncryption; // @synthesize sessionEncryption=_sessionEncryption;
@property(retain, nonatomic) id <HMDDataStreamTransport> transport; // @synthesize transport=_transport;
@property(nonatomic) __weak id <HMDDataStreamDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)transportDidOpen:(id)arg1;
- (void)transportDidClose:(id)arg1;
- (void)transport:(id)arg1 didReceiveRawFrame:(id)arg2;
- (void)transport:(id)arg1 didFailWithError:(id)arg2;
- (void)sendMessage:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)addProtocol:(id)arg1;
- (void)close;
- (void)connect;
- (id)initWithTransport:(id)arg1 sessionEncryption:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

