//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class HAPSecuritySessionEncryption, HMFNetAddress;

@interface HMDDataStreamSetup : NSObject
{
    HMFNetAddress *_remoteNetAddress;
    long long _remoteTcpPort;
    HAPSecuritySessionEncryption *_sessionEncryption;
}

@property(retain, nonatomic) HAPSecuritySessionEncryption *sessionEncryption; // @synthesize sessionEncryption=_sessionEncryption;
@property(nonatomic) long long remoteTcpPort; // @synthesize remoteTcpPort=_remoteTcpPort;
@property(retain, nonatomic) HMFNetAddress *remoteNetAddress; // @synthesize remoteNetAddress=_remoteNetAddress;
- (void).cxx_destruct;
- (BOOL)isComplete;

@end

