//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <HomeKitDaemon/HMDTLVBase.h>

#import "HMDTLVCreateParse.h"

@class HMDDataStreamTransportCommand, HMDDataStreamTransportProtocol;

@interface HMDDataStreamTransportSetupConfiguration : HMDTLVBase <HMDTLVCreateParse>
{
    HMDDataStreamTransportCommand *_command;
    HMDDataStreamTransportProtocol *_protocol;
}

@property(readonly, copy, nonatomic) HMDDataStreamTransportProtocol *protocol; // @synthesize protocol=_protocol;
@property(readonly, copy, nonatomic) HMDDataStreamTransportCommand *command; // @synthesize command=_command;
- (void).cxx_destruct;
- (void)description:(id)arg1 indent:(id)arg2;
- (id)tlvData;
- (BOOL)_parseFromTLVData;
- (id)initWithCommand:(id)arg1 protocol:(id)arg2;

@end

