//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CKContextClient, NSArray, NSString;

@interface CTCategories : NSObject
{
    NSString *_indexVersionId;
    CKContextClient *_client;
}

+ (id)sharedCategories;
+ (void)initialize;
@property(retain, nonatomic) CKContextClient *client; // @synthesize client=_client;
- (void).cxx_destruct;
- (void)categoriesForDomainURLs:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)categoriesForDomainURLs:(id)arg1 responseWithError:(CDUnknownBlockType)arg2;
- (void)categoriesForDomainURLs:(id)arg1 response:(CDUnknownBlockType)arg2;
- (void)categoriesForDomainNames:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)categoriesForDomainNames:(id)arg1 responseWithError:(CDUnknownBlockType)arg2;
- (void)categoriesForDomainNames:(id)arg1 response:(CDUnknownBlockType)arg2;
- (void)categoriesForBundleIDs:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)categoriesForBundleIDs:(id)arg1 responseWithError:(CDUnknownBlockType)arg2;
- (void)categoriesForBundleIDs:(id)arg1 response:(CDUnknownBlockType)arg2;
- (void)categoryForDomainURL:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)categoryForDomainURL:(id)arg1 responseWithError:(CDUnknownBlockType)arg2;
- (void)categoryForDomainURL:(id)arg1 response:(CDUnknownBlockType)arg2;
- (void)categoryForDomainName:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)categoryForDomainName:(id)arg1 responseWithError:(CDUnknownBlockType)arg2;
- (void)categoryForDomainName:(id)arg1 response:(CDUnknownBlockType)arg2;
- (void)categoryForBundleID:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)categoryForBundleID:(id)arg1 responseWithError:(CDUnknownBlockType)arg2;
- (void)categoryForBundleID:(id)arg1 response:(CDUnknownBlockType)arg2;
@property(readonly, copy) NSArray *availableCategoryIDs;
- (id)init;

@end

