//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <IMDaemonCore/IMDCKAbstractSyncController.h>

@class CKOperationConfiguration, CKRecordID, IMDCKDatabaseManager, IMDRecordZoneManager, NSDate, NSError, NSNumber, NSObject<OS_dispatch_queue>;

@interface IMDCKExitManager : IMDCKAbstractSyncController
{
    BOOL _fetchedExitDateOnLaunch;
    CKRecordID *_exitRecordID;
    CKOperationConfiguration *_exitConfigurtation;
    NSNumber *_saltZoneCreatedOverride;
    NSObject<OS_dispatch_queue> *_ckQueue;
    IMDRecordZoneManager *_recordZoneManager;
    IMDCKDatabaseManager *_databaseManager;
    NSDate *_exitRecordDate;
    NSError *_errorFetchingExitDate;
}

+ (id)sharedInstance;
@property(nonatomic) BOOL fetchedExitDateOnLaunch; // @synthesize fetchedExitDateOnLaunch=_fetchedExitDateOnLaunch;
@property(retain, nonatomic) NSError *errorFetchingExitDate; // @synthesize errorFetchingExitDate=_errorFetchingExitDate;
@property(retain, nonatomic) NSDate *exitRecordDate; // @synthesize exitRecordDate=_exitRecordDate;
@property(retain, nonatomic) IMDCKDatabaseManager *databaseManager; // @synthesize databaseManager=_databaseManager;
@property(retain, nonatomic) IMDRecordZoneManager *recordZoneManager; // @synthesize recordZoneManager=_recordZoneManager;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *ckQueue; // @synthesize ckQueue=_ckQueue;
@property(retain, nonatomic) NSNumber *saltZoneCreatedOverride; // @synthesize saltZoneCreatedOverride=_saltZoneCreatedOverride;
@property(retain, nonatomic) CKOperationConfiguration *exitConfigurtation; // @synthesize exitConfigurtation=_exitConfigurtation;
@property(retain, nonatomic) CKRecordID *exitRecordID; // @synthesize exitRecordID=_exitRecordID;
- (void)sendCloudKitZoneFetchRequestToNoteFeatureIsOn;
- (void)submitCloudKitMetricWithData:(id)arg1 operationGroupName:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (BOOL)_serverAllowsMetricSubmission;
- (void)submitCloudKitMetricWithOperationGroupName:(id)arg1;
- (void)writeSyncCompletedRecordWithDate:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)writeInitialSyncCompletedRecordIfNeeded;
- (BOOL)_saltZoneCreated;
- (void)_scheduleOperation:(id)arg1;
- (id)syncCompleteRecordID;
- (void)deleteExitRecordWithCompletion:(CDUnknownBlockType)arg1;
- (void)_fetchExitRecordDateWithCompletion:(CDUnknownBlockType)arg1;
- (void)exitRecordDateWithCompletion:(CDUnknownBlockType)arg1;
- (void)writeExitRecordWithDate:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)handleNotificationForSubscriptionID:(id)arg1;
- (void)_setUpSubscription;
- (void)dealloc;
- (id)init;
- (id)initRecordZoneManager:(id)arg1 databaseManager:(id)arg2;

@end

