//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CKContainer;

@interface IMDCKDatabaseManager : NSObject
{
    CKContainer *_truthContainer;
}

+ (id)sharedInstance;
@property(readonly, nonatomic) CKContainer *truthContainer; // @synthesize truthContainer=_truthContainer;
- (id)truthDatabase;
- (void)dealloc;
- (id)init;

@end

