//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IMDCKUtilities : NSObject
{
    BOOL _useDeprecatedApi;
}

+ (id)sharedInstance;
+ (id)im_AKSecurityLevelKey;
@property(nonatomic) BOOL useDeprecatedApi; // @synthesize useDeprecatedApi=_useDeprecatedApi;
- (void)logDumpAndSendMessageTo:(id)arg1 forHours:(int)arg2;
- (BOOL)_isLogDumpingEnabled;
- (BOOL)errorIndicatesIdentityWasLost:(id)arg1;
- (id)lastDeviceBackUpDate;
- (id)newfilteredArrayRemovingCKRecordIDDupes:(id)arg1;
- (id)newfilteredArrayRemovingCKRecordDupes:(id)arg1;
- (BOOL)deviceConditionsAllowPeriodicSync;
- (void)primaryAccountHasiCloudBackupEnabledWithCompletion:(CDUnknownBlockType)arg1;
- (id)_personIdFromAccount:(id)arg1;
- (void)fetchiCloudAccountPersonID:(CDUnknownBlockType)arg1;
- (void)_fetchPrimaryAccountWithCompletion:(CDUnknownBlockType)arg1;
- (void)setiCloudSettingsSwitchEnabled:(_Bool)arg1;
- (id)_accountStore;
- (BOOL)errorIndicatesZoneNotCreated:(id)arg1;
- (id)extractRecordIDsDeletedFromCKPartialError:(id)arg1;
- (BOOL)acceptableErrorCodeWhileDeleting:(id)arg1;
- (BOOL)isRecoverableCloudKitError:(id)arg1 withRetryInterval:(id *)arg2;
- (BOOL)errorIndicatesDeviceConditionsDontAllowSync:(id)arg1;
- (BOOL)CKPartialError:(id)arg1 onlyHasErrorCodes:(id)arg2;
- (BOOL)CKPartialErrorOnlyHasQuotaExceededError:(id)arg1;
- (BOOL)CKPartialError:(id)arg1 hasErrorCode:(id)arg2;
- (id)extractServerRecordFromCKServerErrorRecordChanged:(id)arg1;
- (id)_errorsFromPartialError:(id)arg1;
- (BOOL)_isCKErrorPartialFailure:(id)arg1;
- (id)recordNameForMessageWithGUID:(id)arg1 usingSalt:(id)arg2;
- (void)presentCloudKitDebugUIWithString:(id)arg1 internalOnly:(BOOL)arg2;
- (BOOL)_shouldPresentDebugCloudKitPopUP;
- (void)fetchCloudKitAccountStatusWithCompletion:(CDUnknownBlockType)arg1;
- (id)_createAccountError:(id)arg1;
- (void)_checkEligibilityWithLoggedInAccountWithCompletion:(CDUnknownBlockType)arg1;
- (BOOL)_accountInfoWithCompletionHandler:(CDUnknownBlockType)arg1;
- (BOOL)_checkEligibilityWithAccountInfo:(id)arg1;
- (id)_authenticationController;
- (BOOL)accountIsVerifiedForMOCAndSafeForCacheDelete;
- (BOOL)cacheDeleteEnabled;
- (BOOL)_serverAllowsCacheDelete;
- (void)_resetKeepMessagesSettingandBroadcastToAllDevices;
- (void)setCloudKitSyncingEnabled:(BOOL)arg1;
- (BOOL)cloudKitSyncingEnabled;
- (long long)_mininimumServerBagClientValue;
- (void)checkiCloudQuota:(CDUnknownBlockType)arg1;
- (unsigned long long)messageDatabaseSize;
- (void)isFirstSyncWithCompletion:(CDUnknownBlockType)arg1;
- (BOOL)shouldForceArchivedMessagesSync;
- (BOOL)shouldUseDevContainer;
- (void)broadcastInstantStateChangeNotification;
- (id)init;
- (id)_truthDatabase;
- (id)_truthContainer;
- (void)isEligibleForTruthZoneWithCompletionDeprecated:(CDUnknownBlockType)arg1;
- (void)account:(id)arg1 fetchCloudKitAccountStatusWithCompletion:(CDUnknownBlockType)arg2;
- (BOOL)securityLevelIsEligibleForTruthZone:(unsigned long long)arg1;
- (void)fetchSecurityLevelForAccount:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (id)accountWithDSID:(id)arg1;
- (id)accountDSID:(id)arg1;
- (id)_accountManager;

@end

