//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IMDCKAbstractSyncController : NSObject
{
    BOOL _isSyncing;
}

@property(nonatomic) BOOL isSyncing; // @synthesize isSyncing=_isSyncing;
- (void)addSyncDebuggingInfoToDictionary:(id)arg1;
- (id)syncStateDebuggingInfo:(id)arg1;
- (id)readPersistentValueForKey:(id)arg1;
- (BOOL)readPersistentBoolForKey:(id)arg1;
- (void)writePersistentValue:(id)arg1 forKey:(id)arg2;
- (void)writePersistentBool:(BOOL)arg1 forKey:(id)arg2;
- (id)prefsWriter;
- (id)ckUtilities;

@end

