//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_source>, WBSSocket;

@interface WBSCyclerSecondaryDeviceCoordinator : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
    WBSSocket *_connection;
    NSObject<OS_dispatch_source> *_timeoutTimer;
    id <WBSCyclerSecondaryDeviceCoordinatorDelegate> _delegate;
}

@property __weak id <WBSCyclerSecondaryDeviceCoordinatorDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)_descriptionForErrorCode:(long long)arg1;
- (id)_errorWithCode:(long long)arg1;
- (void)_timeoutTimerDidFire;
- (void)_didReceiveData:(id)arg1;
- (void)_didEncounterError:(id)arg1;
- (void)_didConnect;
- (void)sendDataToPrimaryDevice:(id)arg1;
- (void)connectToPrimaryDeviceAtAddress:(id)arg1 port:(unsigned long long)arg2 timeout:(double)arg3;
- (id)init;

@end

