//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_source>, WBSSocketServer;

@interface WBSCyclerPrimaryDeviceCoordinator : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
    WBSSocketServer *_server;
    NSMutableArray *_connections;
    NSObject<OS_dispatch_source> *_timeoutTimer;
    unsigned long long _expectedNumberOfSecondaryDevices;
    id <WBSCyclerPrimaryDeviceCoordinatorDelegate> _delegate;
}

@property __weak id <WBSCyclerPrimaryDeviceCoordinatorDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)_descriptionForErrorCode:(long long)arg1;
- (id)_errorWithCode:(long long)arg1;
- (void)_timeoutTimerDidFire;
- (void)_handleConnection:(id)arg1;
- (void)_didReceiveData:(id)arg1 fromSecondaryDevice:(unsigned long long)arg2;
- (void)_didEncounterError:(id)arg1;
- (void)_didConnectToAllSecondaryDevices;
- (void)_didReceivePortAssignment;
- (void)sendDataToAllSecondaryDevices:(id)arg1;
- (void)sendData:(id)arg1 toSecondaryDevice:(unsigned long long)arg2;
- (void)startCoordinatingWithExpectedNumberOfSecondaryDevices:(unsigned long long)arg1 timeout:(double)arg2;
- (id)init;

@end

