//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <SafariShared/WBSParsecSearchResult.h>

@class SFFlight;

@interface WBSParsecSearchFlightsResult : WBSParsecSearchResult
{
    SFFlight *_sfFlight;
    unsigned long long _selectedLegIndex;
}

+ (id)_specializedSchema;
- (void).cxx_destruct;
- (void)getFlight:(id *)arg1 selectedLegIndex:(unsigned long long *)arg2;
@property unsigned long long selectedLegIndex;
@property(readonly) SFFlight *sfFlight;
- (void)_loadFlightInfoWithCard:(id)arg1;
- (void)setSfSearchResultValue:(id)arg1;
- (id)initWithDictionary:(id)arg1;

@end

