//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSNumber, NSString;

@protocol WBSParsecBag <NSObject>
@property(readonly, nonatomic) NSNumber *safari_autoplayFeedbackSamplingPercentage;
@property(readonly, nonatomic) NSNumber *searchRenderTimeout;
@property(readonly, copy, nonatomic) NSArray *enabledDomains;
@property(readonly, copy, nonatomic) NSString *firstUseLearnMoreText;
@property(readonly, copy, nonatomic) NSString *firstUseDescriptionText;
@property(readonly, nonatomic, getter=isEnabled) BOOL enabled;
@end

