//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_source>;

@interface WBSSocketServer : NSObject
{
    int _socketDescriptor;
    unsigned long long _port;
    NSObject<OS_dispatch_queue> *_queue;
    NSObject<OS_dispatch_source> *_source;
    NSMutableArray *_blocksAwaitingPortAssignment;
}

@property unsigned long long port; // @synthesize port=_port;
- (void).cxx_destruct;
- (void)_closeOnInternalQueue;
- (id)_acceptConnectionOnInternalQueue;
- (void)waitForPortAssignmentWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)startAcceptingConnectionsWithHandler:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (id)initWithPort:(unsigned long long)arg1;
- (id)init;

@end

