//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AFAudioPlaybackRequest, NSData, NSDictionary, NSURL;

@interface AFAudioPlaybackRequestBuilder : NSObject
{
    AFAudioPlaybackRequest *_baseObject;
    NSURL *_itemURL;
    NSData *_itemData;
    long long _numberOfLoops;
    float _volume;
    double _fadeInDuration;
    double _fadeOutDuration;
    NSDictionary *_userInfo;
    struct _builderFlags {
        unsigned int isDirty:1;
        unsigned int hasItemURL:1;
        unsigned int hasItemData:1;
        unsigned int hasNumberOfLoops:1;
        unsigned int hasVolume:1;
        unsigned int hasFadeInDuration:1;
        unsigned int hasFadeOutDuration:1;
        unsigned int hasUserInfo:1;
    } _builderFlags;
}

- (void).cxx_destruct;
- (id)build;
- (id)setUserInfo:(id)arg1;
- (id)setFadeOutDuration:(double)arg1;
- (id)setFadeInDuration:(double)arg1;
- (id)setVolume:(float)arg1;
- (id)setNumberOfLoops:(long long)arg1;
- (id)setItemData:(id)arg1;
- (id)setItemURL:(id)arg1;
- (id)initWithBaseObject:(id)arg1;
- (id)init;

@end

