//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AFAudioPlaybackRequest, AFClientConfiguration;

@interface AFClientConfigurationBuilder : NSObject
{
    AFClientConfiguration *_baseObject;
    BOOL _isDeviceInSetupFlow;
    BOOL _isDeviceInCarDNDMode;
    AFAudioPlaybackRequest *_tapToSiriAudioPlaybackRequest;
    AFAudioPlaybackRequest *_twoShotAudioPlaybackRequest;
    struct _builderFlags {
        unsigned int isDirty:1;
        unsigned int hasIsDeviceInSetupFlow:1;
        unsigned int hasIsDeviceInCarDNDMode:1;
        unsigned int hasTapToSiriAudioPlaybackRequest:1;
        unsigned int hasTwoShotAudioPlaybackRequest:1;
    } _builderFlags;
}

- (void).cxx_destruct;
- (id)build;
- (id)setTwoShotAudioPlaybackRequest:(id)arg1;
- (id)setTapToSiriAudioPlaybackRequest:(id)arg1;
- (id)setIsDeviceInCarDNDMode:(BOOL)arg1;
- (id)setIsDeviceInSetupFlow:(BOOL)arg1;
- (id)initWithBaseObject:(id)arg1;
- (id)init;

@end

