//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AFExperimentGroup, NSDictionary, NSString;

@interface AFExperimentGroupBuilder : NSObject
{
    AFExperimentGroup *_baseObject;
    NSString *_identifier;
    unsigned long long _allocation;
    NSDictionary *_properties;
    struct _builderFlags {
        unsigned int isDirty:1;
        unsigned int hasIdentifier:1;
        unsigned int hasAllocation:1;
        unsigned int hasProperties:1;
    } _builderFlags;
}

- (void).cxx_destruct;
- (id)build;
- (id)setProperties:(id)arg1;
- (id)setAllocation:(unsigned long long)arg1;
- (id)setIdentifier:(id)arg1;
- (id)initWithBaseObject:(id)arg1;
- (id)init;

@end

