//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AFExperiment, NSDictionary, NSString;

@interface AFExperimentBuilder : NSObject
{
    AFExperiment *_baseObject;
    NSString *_configurationIdentifier;
    NSString *_configurationVersion;
    NSString *_deploymentGroupIdentifier;
    NSDictionary *_deploymentGroupProperties;
    long long _deploymentReason;
    struct _builderFlags {
        unsigned int isDirty:1;
        unsigned int hasConfigurationIdentifier:1;
        unsigned int hasConfigurationVersion:1;
        unsigned int hasDeploymentGroupIdentifier:1;
        unsigned int hasDeploymentGroupProperties:1;
        unsigned int hasDeploymentReason:1;
    } _builderFlags;
}

- (void).cxx_destruct;
- (id)build;
- (id)setDeploymentReason:(long long)arg1;
- (id)setDeploymentGroupProperties:(id)arg1;
- (id)setDeploymentGroupIdentifier:(id)arg1;
- (id)setConfigurationVersion:(id)arg1;
- (id)setConfigurationIdentifier:(id)arg1;
- (id)initWithBaseObject:(id)arg1;
- (id)init;

@end

