//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AFExperimentContext, NSDictionary;

@interface AFExperimentContextBuilder : NSObject
{
    AFExperimentContext *_baseObject;
    NSDictionary *_experimentsByConfigurationIdentifier;
    struct _builderFlags {
        unsigned int isDirty:1;
        unsigned int hasExperimentsByConfigurationIdentifier:1;
    } _builderFlags;
}

- (void).cxx_destruct;
- (id)build;
- (id)setExperimentsByConfigurationIdentifier:(id)arg1;
- (id)initWithBaseObject:(id)arg1;
- (id)init;

@end

