//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AFMemoryInfo;

@interface AFMemoryInfoBuilder : NSObject
{
    AFMemoryInfo *_baseObject;
    unsigned long long _virtualMemorySizeInBytes;
    int _numberOfRegions;
    int _pageSizeInBytes;
    unsigned long long _residentMemorySizeInBytes;
    unsigned long long _peakResidentMemorySizeInBytes;
    unsigned long long _physicalMemoryFootprintInBytes;
    struct _builderFlags {
        unsigned int isDirty:1;
        unsigned int hasVirtualMemorySizeInBytes:1;
        unsigned int hasNumberOfRegions:1;
        unsigned int hasPageSizeInBytes:1;
        unsigned int hasResidentMemorySizeInBytes:1;
        unsigned int hasPeakResidentMemorySizeInBytes:1;
        unsigned int hasPhysicalMemoryFootprintInBytes:1;
    } _builderFlags;
}

- (void).cxx_destruct;
- (id)build;
- (id)setPhysicalMemoryFootprintInBytes:(unsigned long long)arg1;
- (id)setPeakResidentMemorySizeInBytes:(unsigned long long)arg1;
- (id)setResidentMemorySizeInBytes:(unsigned long long)arg1;
- (id)setPageSizeInBytes:(int)arg1;
- (id)setNumberOfRegions:(int)arg1;
- (id)setVirtualMemorySizeInBytes:(unsigned long long)arg1;
- (id)initWithBaseObject:(id)arg1;
- (id)init;

@end

