//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AFNotifyObserverDelegate.h"

@class AFNotifyObserver, NSMutableArray, NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_source>, NSString;

@interface AFMyriadMonitor : NSObject <AFNotifyObserverDelegate>
{
    long long _state;
    NSObject<OS_dispatch_source> *_timer;
    struct __CFNotificationCenter *_center;
    NSObject<OS_dispatch_queue> *_myriadMonitorQueue;
    NSMutableArray *_completions;
    AFNotifyObserver *_wonObserver;
    AFNotifyObserver *_lostObserver;
    AFNotifyObserver *_beganObserver;
}

+ (void)clear;
+ (void)waitForMyriadDecisionWithCompletion:(CDUnknownBlockType)arg1;
+ (id)sharedMonitor;
- (void).cxx_destruct;
- (void)resultSeenWithValue:(BOOL)arg1;
- (void)_flushCompletions:(BOOL)arg1;
- (void)clear;
- (void)addCompletion:(CDUnknownBlockType)arg1;
- (void)setDecisionIsPending;
- (void)notifyObserver:(id)arg1 didReceiveNotificationWithToken:(int)arg2;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

