//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AFRequestInfo, AFSiriActivationListener;

@protocol AFSiriActivationListenerDelegate <NSObject>
- (void)siriActivationListener:(AFSiriActivationListener *)arg1 handleActivationWithRequestInfo:(AFRequestInfo *)arg2;

@optional
- (void)siriActivationListener:(AFSiriActivationListener *)arg1 handlePrewarmForRequestInfo:(AFRequestInfo *)arg2;
@end

