//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AFSpeechSynthesisRecord, NSString;

@interface AFSpeechSynthesisRecordBuilder : NSObject
{
    AFSpeechSynthesisRecord *_baseObject;
    NSString *_utterance;
    unsigned long long _beginTimestamp;
    unsigned long long _endTimestamp;
    struct _builderFlags {
        unsigned int isDirty:1;
        unsigned int hasUtterance:1;
        unsigned int hasBeginTimestamp:1;
        unsigned int hasEndTimestamp:1;
    } _builderFlags;
}

- (void).cxx_destruct;
- (id)build;
- (id)setEndTimestamp:(unsigned long long)arg1;
- (id)setBeginTimestamp:(unsigned long long)arg1;
- (id)setUtterance:(id)arg1;
- (id)initWithBaseObject:(id)arg1;
- (id)init;

@end

