//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@class NSBox, NSStackView, NSTextField;

__attribute__((visibility("hidden")))
@interface AutomaticPasswordPopoverViewController : NSViewController
{
    id <AutomaticPasswordPopoverViewControllerDelegate> _delegate;
    NSBox *_horizontalDivider;
    NSStackView *_popoverTitleStackView;
    NSTextField *_popoverTitleLabel;
    NSTextField *_descriptionTextField;
    NSStackView *_rootStackView;
}

@property(nonatomic) __weak NSStackView *rootStackView; // @synthesize rootStackView=_rootStackView;
@property(nonatomic) __weak NSTextField *descriptionTextField; // @synthesize descriptionTextField=_descriptionTextField;
@property(nonatomic) __weak NSTextField *popoverTitleLabel; // @synthesize popoverTitleLabel=_popoverTitleLabel;
@property(nonatomic) __weak NSStackView *popoverTitleStackView; // @synthesize popoverTitleStackView=_popoverTitleStackView;
@property(nonatomic) __weak NSBox *horizontalDivider; // @synthesize horizontalDivider=_horizontalDivider;
@property(nonatomic) __weak id <AutomaticPasswordPopoverViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_notifyDelegateToUseStrongPassword:(BOOL)arg1;
- (void)doNotUseStrongPassword:(id)arg1;
- (void)useStrongPassword:(id)arg1;
- (void)viewDidDisappear;
- (void)awakeFromNib;

@end

