//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate;

__attribute__((visibility("hidden")))
@interface FaviconRecord : NSObject
{
    NSDate *_dateAdded;
    struct CGSize _size;
}

+ (id)new;
@property(readonly, nonatomic) struct CGSize size; // @synthesize size=_size;
@property(readonly, nonatomic) NSDate *dateAdded; // @synthesize dateAdded=_dateAdded;
- (void).cxx_destruct;
- (id)initWithDateAdded:(id)arg1 size:(struct CGSize)arg2;
- (id)init;

@end

