//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface FaviconProviderRecordCache : NSObject
{
    NSMutableDictionary *_iconURLStringToRecordDictionary;
    NSMutableDictionary *_iconUUIDToURLStringDictionary;
}

+ (id)new;
- (void).cxx_destruct;
- (void)removeRecordForIconUUIDs:(id)arg1;
- (void)removeAllRecords;
- (id)dateAddedForFaviconURLString:(id)arg1 getSize:(struct CGSize *)arg2;
- (void)setDateAdded:(id)arg1 forFaviconURLString:(id)arg2 iconUUID:(id)arg3 iconSize:(struct CGSize)arg4;
- (id)init;

@end

