//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@class NSButton, NSPopover, NSString, NSTextField, WBSSavedPassword;

__attribute__((visibility("hidden")))
@interface PasswordsAuditingPopoverViewController : NSViewController
{
    NSString *_duplicatedPasswordDomain;
    NSPopover *_popover;
    id <PasswordsAuditingHandler> _passwordAuditingHandler;
    WBSSavedPassword *_auditingSavedPassword;
    NSTextField *_passwordsAuditingWarningLabel;
    NSButton *_changePasswordButton;
}

@property(nonatomic) __weak NSButton *changePasswordButton; // @synthesize changePasswordButton=_changePasswordButton;
@property(nonatomic) __weak NSTextField *passwordsAuditingWarningLabel; // @synthesize passwordsAuditingWarningLabel=_passwordsAuditingWarningLabel;
@property(retain, nonatomic) WBSSavedPassword *auditingSavedPassword; // @synthesize auditingSavedPassword=_auditingSavedPassword;
@property(nonatomic) __weak id <PasswordsAuditingHandler> passwordAuditingHandler; // @synthesize passwordAuditingHandler=_passwordAuditingHandler;
- (void).cxx_destruct;
- (void)closePopover;
- (void)showPopoverWithPositioningView:(id)arg1;
- (void)_changePassword:(id)arg1;
- (void)_updateWarningLabelStringValue;
- (void)viewDidLoad;

@end

