//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GEOApplicationAuditToken, GEOETARequest;

@protocol _GEOETARequesterServerProxy <NSObject>
- (void)cancelSimpleETARequest:(GEOETARequest *)arg1;
- (void)startSimpleETARequest:(GEOETARequest *)arg1 auditToken:(GEOApplicationAuditToken *)arg2 requestMode:(int)arg3 finished:(void (^)(GEOETAResponse *))arg4 networkActivity:(void (^)(BOOL))arg5 error:(void (^)(NSError *))arg6;
@end

