//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (GEOCacheUsageMonitor)
+ (id)keyStringForCacheMissWithLoadReason:(unsigned char)arg1 missType:(int)arg2 tileStyle:(int)arg3 tileZoom:(unsigned int)arg4;
+ (id)keyStringForCacheHitWithLoadReason:(unsigned char)arg1 tileSource:(unsigned char)arg2 tileStyle:(int)arg3 tileZoom:(unsigned int)arg4;
- (void)cacheMissParameters:(CDUnknownBlockType)arg1;
- (void)cacheHitParameters:(CDUnknownBlockType)arg1;
@end

