//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IMCTSMSUtilities : NSObject
{
}

+ (BOOL)IMMessagesFilteringSettingForPreferedSubscription;
+ (BOOL)MMSRestrictedModeEnabledForPhoneNumber:(id)arg1 reset:(BOOL)arg2;
+ (BOOL)IMMMSRestrictedModeEnabledForPhoneNumber:(id)arg1;
+ (id)IMMMSEmailAddressToMatchForPhoneNumber:(id)arg1;
+ (unsigned long long)IMiMessageMaxTransferVideoFileSizeForWifiForPhoneNumber:(unsigned long long *)arg1 cellSize:(unsigned long long *)arg2 serverConfigurationBag:(id)arg3 phoneNumber:(id)arg4;
+ (unsigned long long)IMiMessageMaxTransferAudioFileSizeForWifiForPhoneNumber:(unsigned long long *)arg1 cellSize:(unsigned long long *)arg2 serverConfigurationBag:(id)arg3 phoneNumber:(id)arg4;
+ (void)IMiMessageMaxTransferFileSizeForWifiForPhoneNumber:(unsigned long long *)arg1 cellSize:(unsigned long long *)arg2 serverConfigurationBag:(id)arg3 phoneNumber:(id)arg4;
+ (double)IMMMSMaximumDurationWithPreset:(id)arg1 phoneNumber:(id)arg2;
+ (double)IMMMSMaximumVideoDurationForPhoneNumber:(id)arg1;
+ (double)IMMMSMaximumAudioDurationForPhoneNumber:(id)arg1;
+ (BOOL)IMMMSSupportsH264VideoForPhoneNumber:(id)arg1;
+ (int)IMMMSMaxImageDimensionForPhoneNumber:(id)arg1;
+ (int)IMMMSMaxRecipientsForPhoneNumber:(id)arg1;
+ (BOOL)IMMMSGroupTextOnlyMessagesSendAsMMSForPhoneNumber:(id)arg1;
+ (int)IMMMSMaximumMessageByteCountForPhoneNumber:(id)arg1;
+ (int)IMMMSMaximumSlideCountForPhoneNumber:(id)arg1;
+ (BOOL)IMMMSSupportedAndConfiguredForPhoneNumber:(id)arg1;
+ (BOOL)IMMMSEnabledForPhoneNumber:(id)arg1;
+ (BOOL)IMReadMMSUserOverrideForPhoneNumber:(id)arg1;

@end

