//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CloudPhotoLibrary/CPLCloudKitBaseSetupTask.h>

#import "CPLEngineTransportSetupTask.h"

@class NSString;

@interface CPLCloudKitSetupTask : CPLCloudKitBaseSetupTask <CPLEngineTransportSetupTask>
{
    CDUnknownBlockType _completionHandler;
    BOOL _shouldUpdateDisabledFeatures;
}

@property(readonly, nonatomic) BOOL shouldUpdateDisabledFeatures; // @synthesize shouldUpdateDisabledFeatures=_shouldUpdateDisabledFeatures;
- (void).cxx_destruct;
- (void)runOperations;
- (void)fetchUserRecord;
- (id)initWithController:(id)arg1 updateDisabledFeatures:(BOOL)arg2 completionHandler:(CDUnknownBlockType)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(nonatomic) BOOL foreground;
@property(readonly) unsigned long long hash;
@property(nonatomic) long long minimumQualityOfService;
@property(readonly) Class superclass;
@property(retain, nonatomic) id <CPLEngineTransportGroup> transportGroup;

@end

