//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CloudPhotoLibrary/CPLCloudKitTransportTask.h>

#import "CPLEngineTransportDeleteTransportScopeTask.h"

@class CPLCloudKitScope, CPLEngineScope, NSString;

@interface CPLCloudKitDeleteTransportScopeTask : CPLCloudKitTransportTask <CPLEngineTransportDeleteTransportScopeTask>
{
    CDUnknownBlockType _completionHandler;
    CPLCloudKitScope *_cloudKitScope;
    CPLEngineScope *_scope;
}

@property(readonly, nonatomic) CPLEngineScope *scope; // @synthesize scope=_scope;
@property(readonly, nonatomic) CPLCloudKitScope *cloudKitScope; // @synthesize cloudKitScope=_cloudKitScope;
- (void).cxx_destruct;
- (void)runOperations;
- (id)initWithController:(id)arg1 cloudKitScope:(id)arg2 scope:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(nonatomic) BOOL foreground;
@property(readonly) unsigned long long hash;
@property(nonatomic) long long minimumQualityOfService;
@property(readonly) Class superclass;
@property(retain, nonatomic) id <CPLEngineTransportGroup> transportGroup;

@end

