//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CloudPhotoLibrary/CPLCloudKitTransportTask.h>

#import "CPLEngineTransportAcceptMomentShareTask.h"

@class CPLMomentShare, NSData, NSString;

@interface CPLCloudKitAcceptMomentShareTask : CPLCloudKitTransportTask <CPLEngineTransportAcceptMomentShareTask>
{
    CPLMomentShare *_momentShare;
    NSData *_momentShareTransportScope;
    CDUnknownBlockType _completionHandler;
}

- (void).cxx_destruct;
- (void)_handleShareURL:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_acceptMomentShareWithShareURL:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)runOperations;
- (id)initWithController:(id)arg1 momentShare:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(nonatomic) BOOL foreground;
@property(readonly) unsigned long long hash;
@property(nonatomic) long long minimumQualityOfService;
@property(readonly) Class superclass;
@property(retain, nonatomic) id <CPLEngineTransportGroup> transportGroup;

@end

