//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

@class LAContext, NSArray, NSButton, NSPopUpButton, NSSecureTextField, SFIconView;

@interface LARUIAuthenticationDialog : NSWindowController
{
    NSArray *_adminNames;
    id <LARUIAuthenticationDialogDelegate> _delegate;
    SFIconView *_iconView;
    NSPopUpButton *_userNamePopup;
    NSSecureTextField *_userPasswordField;
    NSButton *_okButton;
    NSButton *_cancelButton;
    LAContext *_context;
    CDUnknownBlockType _reply;
}

@property(copy, nonatomic) CDUnknownBlockType reply; // @synthesize reply=_reply;
@property(retain, nonatomic) LAContext *context; // @synthesize context=_context;
@property __weak NSButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property __weak NSButton *okButton; // @synthesize okButton=_okButton;
@property __weak NSSecureTextField *userPasswordField; // @synthesize userPasswordField=_userPasswordField;
@property __weak NSPopUpButton *userNamePopup; // @synthesize userNamePopup=_userNamePopup;
@property __weak SFIconView *iconView; // @synthesize iconView=_iconView;
@property(nonatomic) __weak id <LARUIAuthenticationDialogDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_setEnabled:(BOOL)arg1;
- (id)_adminNamesWithError:(id *)arg1;
- (void)_setupWindow;
- (void)cancelClicked:(id)arg1;
- (void)okClicked:(id)arg1;
- (void)windowDidLoad;
- (void)showWindow:(id)arg1;
- (id)initWithContext:(id)arg1;

@end

