//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBCodable.h"

#import "NSCopying.h"

@class NSData, NSString, _MRAVOutputDeviceSourceInfoProtobuf;

@interface _MRAVOutputDeviceDescriptorProtobuf : PBCodable <NSCopying>
{
    float _batteryLevel;
    int _deviceSubType;
    int _deviceType;
    NSString *_groupID;
    NSData *_macAddress;
    NSString *_modelID;
    NSData *_modelSpecificInfoData;
    NSString *_name;
    _MRAVOutputDeviceSourceInfoProtobuf *_sourceInfo;
    NSString *_uniqueIdentifier;
    BOOL _canAccessRemoteAssets;
    BOOL _isGroupLeader;
    BOOL _isGroupable;
    BOOL _isLocalDevice;
    BOOL _isRemoteControllable;
    BOOL _requiresAuthorization;
    BOOL _shouldForceRemoteControlabillity;
    BOOL _supportsExternalScreen;
    struct {
        unsigned int batteryLevel:1;
        unsigned int deviceSubType:1;
        unsigned int deviceType:1;
        unsigned int canAccessRemoteAssets:1;
        unsigned int isGroupLeader:1;
        unsigned int isGroupable:1;
        unsigned int isLocalDevice:1;
        unsigned int isRemoteControllable:1;
        unsigned int requiresAuthorization:1;
        unsigned int shouldForceRemoteControlabillity:1;
        unsigned int supportsExternalScreen:1;
    } _has;
}

@property(retain, nonatomic) _MRAVOutputDeviceSourceInfoProtobuf *sourceInfo; // @synthesize sourceInfo=_sourceInfo;
@property(nonatomic) BOOL shouldForceRemoteControlabillity; // @synthesize shouldForceRemoteControlabillity=_shouldForceRemoteControlabillity;
@property(nonatomic) BOOL requiresAuthorization; // @synthesize requiresAuthorization=_requiresAuthorization;
@property(nonatomic) BOOL supportsExternalScreen; // @synthesize supportsExternalScreen=_supportsExternalScreen;
@property(nonatomic) BOOL isLocalDevice; // @synthesize isLocalDevice=_isLocalDevice;
@property(nonatomic) float batteryLevel; // @synthesize batteryLevel=_batteryLevel;
@property(retain, nonatomic) NSData *modelSpecificInfoData; // @synthesize modelSpecificInfoData=_modelSpecificInfoData;
@property(nonatomic) int deviceSubType; // @synthesize deviceSubType=_deviceSubType;
@property(nonatomic) int deviceType; // @synthesize deviceType=_deviceType;
@property(nonatomic) BOOL isGroupable; // @synthesize isGroupable=_isGroupable;
@property(nonatomic) BOOL isGroupLeader; // @synthesize isGroupLeader=_isGroupLeader;
@property(nonatomic) BOOL isRemoteControllable; // @synthesize isRemoteControllable=_isRemoteControllable;
@property(nonatomic) BOOL canAccessRemoteAssets; // @synthesize canAccessRemoteAssets=_canAccessRemoteAssets;
@property(retain, nonatomic) NSData *macAddress; // @synthesize macAddress=_macAddress;
@property(retain, nonatomic) NSString *modelID; // @synthesize modelID=_modelID;
@property(retain, nonatomic) NSString *groupID; // @synthesize groupID=_groupID;
@property(retain, nonatomic) NSString *uniqueIdentifier; // @synthesize uniqueIdentifier=_uniqueIdentifier;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(readonly, nonatomic) BOOL hasSourceInfo;
@property(nonatomic) BOOL hasShouldForceRemoteControlabillity;
@property(nonatomic) BOOL hasRequiresAuthorization;
@property(nonatomic) BOOL hasSupportsExternalScreen;
@property(nonatomic) BOOL hasIsLocalDevice;
@property(nonatomic) BOOL hasBatteryLevel;
@property(readonly, nonatomic) BOOL hasModelSpecificInfoData;
@property(nonatomic) BOOL hasDeviceSubType;
@property(nonatomic) BOOL hasDeviceType;
@property(nonatomic) BOOL hasIsGroupable;
@property(nonatomic) BOOL hasIsGroupLeader;
@property(nonatomic) BOOL hasIsRemoteControllable;
@property(nonatomic) BOOL hasCanAccessRemoteAssets;
@property(readonly, nonatomic) BOOL hasMacAddress;
@property(readonly, nonatomic) BOOL hasModelID;
@property(readonly, nonatomic) BOOL hasGroupID;
@property(readonly, nonatomic) BOOL hasUniqueIdentifier;
@property(readonly, nonatomic) BOOL hasName;
- (void)dealloc;

@end

