//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBCodable.h"

#import "NSCopying.h"

@class NSMutableArray, NSString, _MRAVOutputDeviceDescriptorProtobuf;

@interface _MRAVEndpointDescriptorProtobuf : PBCodable <NSCopying>
{
    _MRAVOutputDeviceDescriptorProtobuf *_designatedGroupLeader;
    NSString *_instanceIdentifier;
    NSString *_name;
    NSMutableArray *_outputDevices;
    NSString *_uniqueIdentifier;
    BOOL _isLocalEndpoint;
    struct {
        unsigned int isLocalEndpoint:1;
    } _has;
}

+ (Class)outputDevicesType;
@property(retain, nonatomic) NSString *instanceIdentifier; // @synthesize instanceIdentifier=_instanceIdentifier;
@property(nonatomic) BOOL isLocalEndpoint; // @synthesize isLocalEndpoint=_isLocalEndpoint;
@property(retain, nonatomic) _MRAVOutputDeviceDescriptorProtobuf *designatedGroupLeader; // @synthesize designatedGroupLeader=_designatedGroupLeader;
@property(retain, nonatomic) NSMutableArray *outputDevices; // @synthesize outputDevices=_outputDevices;
@property(retain, nonatomic) NSString *uniqueIdentifier; // @synthesize uniqueIdentifier=_uniqueIdentifier;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(readonly, nonatomic) BOOL hasInstanceIdentifier;
@property(nonatomic) BOOL hasIsLocalEndpoint;
@property(readonly, nonatomic) BOOL hasDesignatedGroupLeader;
- (id)outputDevicesAtIndex:(unsigned long long)arg1;
- (unsigned long long)outputDevicesCount;
- (void)addOutputDevices:(id)arg1;
- (void)clearOutputDevices;
@property(readonly, nonatomic) BOOL hasUniqueIdentifier;
@property(readonly, nonatomic) BOOL hasName;
- (void)dealloc;

@end

