//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBCodable.h"

#import "NSCopying.h"

@class NSData, NSString;

@interface _MRDeviceInfoMessageProtobuf : PBCodable <NSCopying>
{
    unsigned long long _protocolVersion;
    NSString *_applicationBundleIdentifier;
    NSString *_applicationBundleVersion;
    NSData *_bluetoothAddress;
    unsigned int _lastSupportedMessageType;
    NSString *_localReceiverPairingIdentity;
    NSString *_localizedModelName;
    NSString *_name;
    unsigned int _sharedQueueVersion;
    NSString *_systemBuildVersion;
    NSString *_systemMediaApplication;
    NSString *_uniqueIdentifier;
    BOOL _allowsPairing;
    BOOL _connected;
    BOOL _supportsACL;
    BOOL _supportsExtendedMotion;
    BOOL _supportsSharedQueue;
    BOOL _supportsSystemPairing;
    struct {
        unsigned int protocolVersion:1;
        unsigned int lastSupportedMessageType:1;
        unsigned int sharedQueueVersion:1;
        unsigned int allowsPairing:1;
        unsigned int connected:1;
        unsigned int supportsACL:1;
        unsigned int supportsExtendedMotion:1;
        unsigned int supportsSharedQueue:1;
        unsigned int supportsSystemPairing:1;
    } _has;
}

@property(retain, nonatomic) NSString *localReceiverPairingIdentity; // @synthesize localReceiverPairingIdentity=_localReceiverPairingIdentity;
@property(nonatomic) unsigned int sharedQueueVersion; // @synthesize sharedQueueVersion=_sharedQueueVersion;
@property(retain, nonatomic) NSData *bluetoothAddress; // @synthesize bluetoothAddress=_bluetoothAddress;
@property(nonatomic) BOOL supportsExtendedMotion; // @synthesize supportsExtendedMotion=_supportsExtendedMotion;
@property(nonatomic) BOOL supportsSharedQueue; // @synthesize supportsSharedQueue=_supportsSharedQueue;
@property(nonatomic) BOOL supportsACL; // @synthesize supportsACL=_supportsACL;
@property(retain, nonatomic) NSString *systemMediaApplication; // @synthesize systemMediaApplication=_systemMediaApplication;
@property(nonatomic) BOOL connected; // @synthesize connected=_connected;
@property(nonatomic) BOOL allowsPairing; // @synthesize allowsPairing=_allowsPairing;
@property(nonatomic) BOOL supportsSystemPairing; // @synthesize supportsSystemPairing=_supportsSystemPairing;
@property(nonatomic) unsigned int lastSupportedMessageType; // @synthesize lastSupportedMessageType=_lastSupportedMessageType;
@property(nonatomic) unsigned long long protocolVersion; // @synthesize protocolVersion=_protocolVersion;
@property(retain, nonatomic) NSString *applicationBundleVersion; // @synthesize applicationBundleVersion=_applicationBundleVersion;
@property(retain, nonatomic) NSString *applicationBundleIdentifier; // @synthesize applicationBundleIdentifier=_applicationBundleIdentifier;
@property(retain, nonatomic) NSString *systemBuildVersion; // @synthesize systemBuildVersion=_systemBuildVersion;
@property(retain, nonatomic) NSString *localizedModelName; // @synthesize localizedModelName=_localizedModelName;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *uniqueIdentifier; // @synthesize uniqueIdentifier=_uniqueIdentifier;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(readonly, nonatomic) BOOL hasLocalReceiverPairingIdentity;
@property(nonatomic) BOOL hasSharedQueueVersion;
@property(readonly, nonatomic) BOOL hasBluetoothAddress;
@property(nonatomic) BOOL hasSupportsExtendedMotion;
@property(nonatomic) BOOL hasSupportsSharedQueue;
@property(nonatomic) BOOL hasSupportsACL;
@property(readonly, nonatomic) BOOL hasSystemMediaApplication;
@property(nonatomic) BOOL hasConnected;
@property(nonatomic) BOOL hasAllowsPairing;
@property(nonatomic) BOOL hasSupportsSystemPairing;
@property(nonatomic) BOOL hasLastSupportedMessageType;
@property(nonatomic) BOOL hasProtocolVersion;
@property(readonly, nonatomic) BOOL hasApplicationBundleVersion;
@property(readonly, nonatomic) BOOL hasApplicationBundleIdentifier;
@property(readonly, nonatomic) BOOL hasSystemBuildVersion;
@property(readonly, nonatomic) BOOL hasLocalizedModelName;
@property(readonly, nonatomic) BOOL hasName;
@property(readonly, nonatomic) BOOL hasUniqueIdentifier;
- (void)dealloc;

@end

