//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBCodable.h"

#import "NSCopying.h"

@class NSString;

@interface _MRNowPlayingPlayerProtobuf : PBCodable <NSCopying>
{
    NSString *_displayName;
    NSString *_identifier;
    BOOL _isDefaultPlayer;
    struct {
        unsigned int isDefaultPlayer:1;
    } _has;
}

@property(nonatomic) BOOL isDefaultPlayer; // @synthesize isDefaultPlayer=_isDefaultPlayer;
@property(retain, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;
@property(retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(nonatomic) BOOL hasIsDefaultPlayer;
@property(readonly, nonatomic) BOOL hasDisplayName;
@property(readonly, nonatomic) BOOL hasIdentifier;
- (void)dealloc;

@end

