//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MRAVEndpoint, MRAVRoutingDiscoverySession, NSArray, NSMutableSet, NSSet, NSTimer;

@interface MRAVReconnaissanceSession : NSObject
{
    BOOL _useWeakMatching;
    BOOL _searchInProgress;
    unsigned int _endpointFeatures;
    NSSet *_matchingOutputDeviceUIDsSet;
    MRAVRoutingDiscoverySession *_discoverySession;
    id _discoverySessionCallbackToken;
    CDUnknownBlockType _callback;
    NSTimer *_timeoutTimer;
    NSMutableSet *_matchingDevicesFound;
    MRAVEndpoint *_unanimousEndpoint;
}

@property(retain, nonatomic) MRAVEndpoint *unanimousEndpoint; // @synthesize unanimousEndpoint=_unanimousEndpoint;
@property(retain, nonatomic) NSMutableSet *matchingDevicesFound; // @synthesize matchingDevicesFound=_matchingDevicesFound;
@property(nonatomic) BOOL searchInProgress; // @synthesize searchInProgress=_searchInProgress;
@property(retain, nonatomic) NSTimer *timeoutTimer; // @synthesize timeoutTimer=_timeoutTimer;
@property(copy, nonatomic) CDUnknownBlockType callback; // @synthesize callback=_callback;
@property(retain, nonatomic) id discoverySessionCallbackToken; // @synthesize discoverySessionCallbackToken=_discoverySessionCallbackToken;
@property(retain, nonatomic) MRAVRoutingDiscoverySession *discoverySession; // @synthesize discoverySession=_discoverySession;
@property(retain, nonatomic) NSSet *matchingOutputDeviceUIDsSet; // @synthesize matchingOutputDeviceUIDsSet=_matchingOutputDeviceUIDsSet;
@property(nonatomic) BOOL useWeakMatching; // @synthesize useWeakMatching=_useWeakMatching;
@property(readonly, nonatomic) unsigned int endpointFeatures; // @synthesize endpointFeatures=_endpointFeatures;
- (void)_endSearch;
- (void)_concludeSearch;
- (void)_timeoutTimerFired:(id)arg1;
- (void)_discoverySessionEndpointsChangedCallback:(id)arg1;
- (void)cancelSearch;
- (void)beginSearchWithTimeout:(double)arg1 completion:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) NSArray *matchingOutputDeviceUIDs;
- (void)dealloc;
- (id)initWithOutputDeviceUIDs:(id)arg1 features:(unsigned int)arg2;

@end

