//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MRAVOutputDeviceSourceInfo, NSData, NSDictionary, NSString, _MRAVOutputDeviceDescriptorProtobuf;

@interface MRAVOutputDevice : NSObject
{
    BOOL _canAccessRemoteAssets;
    BOOL _remoteControllable;
    BOOL _groupLeader;
    BOOL _groupable;
    BOOL _pickedOnPairedDevice;
    BOOL _hasBatteryLevel;
    BOOL _localDevice;
    BOOL _supportsExternalScreen;
    BOOL _requiresAuthorization;
    BOOL _volumeControlAvailable;
    unsigned int _deviceType;
    unsigned int _deviceSubtype;
    float _batteryLevel;
    float _volume;
    NSString *_name;
    NSString *_uid;
    NSString *_modelID;
    NSString *_groupID;
    NSString *_logicalDeviceID;
    NSData *_MACAddress;
    NSDictionary *_modelSpecificInfo;
    NSString *_playingPairedDeviceName;
    MRAVOutputDeviceSourceInfo *_sourceInfo;
    void *_endpoint;
}

+ (id)localDeviceUID;
@property(nonatomic) void *endpoint; // @synthesize endpoint=_endpoint;
@property(nonatomic) float volume; // @synthesize volume=_volume;
@property(readonly, nonatomic) MRAVOutputDeviceSourceInfo *sourceInfo; // @synthesize sourceInfo=_sourceInfo;
@property(readonly, nonatomic, getter=isVolumeControlAvailable) BOOL volumeControlAvailable; // @synthesize volumeControlAvailable=_volumeControlAvailable;
@property(readonly, nonatomic) BOOL requiresAuthorization; // @synthesize requiresAuthorization=_requiresAuthorization;
@property(readonly, nonatomic) BOOL supportsExternalScreen; // @synthesize supportsExternalScreen=_supportsExternalScreen;
@property(readonly, nonatomic, getter=isLocalDevice) BOOL localDevice; // @synthesize localDevice=_localDevice;
@property(readonly, nonatomic) BOOL hasBatteryLevel; // @synthesize hasBatteryLevel=_hasBatteryLevel;
@property(readonly, nonatomic) float batteryLevel; // @synthesize batteryLevel=_batteryLevel;
@property(readonly, nonatomic) unsigned int deviceSubtype; // @synthesize deviceSubtype=_deviceSubtype;
@property(readonly, nonatomic) unsigned int deviceType; // @synthesize deviceType=_deviceType;
@property(readonly, nonatomic, getter=isPickedOnPairedDevice) BOOL pickedOnPairedDevice; // @synthesize pickedOnPairedDevice=_pickedOnPairedDevice;
@property(readonly, nonatomic, getter=isGroupable) BOOL groupable; // @synthesize groupable=_groupable;
@property(readonly, nonatomic, getter=isGroupLeader) BOOL groupLeader; // @synthesize groupLeader=_groupLeader;
@property(readonly, nonatomic, getter=isRemoteControllable) BOOL remoteControllable; // @synthesize remoteControllable=_remoteControllable;
@property(readonly, nonatomic) BOOL canAccessRemoteAssets; // @synthesize canAccessRemoteAssets=_canAccessRemoteAssets;
@property(readonly, nonatomic) NSString *playingPairedDeviceName; // @synthesize playingPairedDeviceName=_playingPairedDeviceName;
@property(readonly, nonatomic) NSDictionary *modelSpecificInfo; // @synthesize modelSpecificInfo=_modelSpecificInfo;
@property(readonly, nonatomic) NSData *MACAddress; // @synthesize MACAddress=_MACAddress;
@property(readonly, nonatomic) NSString *logicalDeviceID; // @synthesize logicalDeviceID=_logicalDeviceID;
@property(readonly, nonatomic) NSString *groupID; // @synthesize groupID=_groupID;
@property(readonly, nonatomic) NSString *modelID; // @synthesize modelID=_modelID;
@property(readonly, nonatomic) NSString *uid; // @synthesize uid=_uid;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, nonatomic) _MRAVOutputDeviceDescriptorProtobuf *descriptor;
- (BOOL)isEqual:(id)arg1;
- (id)description;

@end

