//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <MediaRemote/MRAVEndpoint.h>

#import "NSSecureCoding.h"

@class MRAVDistantOutputDevice, MRDistantExternalDevice, NSArray, NSObject<OS_dispatch_queue>, NSString, NSXPCListenerEndpoint;

@interface MRAVDistantEndpoint : MRAVEndpoint <NSSecureCoding>
{
    NSObject<OS_dispatch_queue> *_accessSerialQueue;
    MRDistantExternalDevice *_distantExternalDevice;
    NSString *_localizedName;
    NSString *_uniqueIdentifier;
    NSString *_instanceIdentifier;
    BOOL _isLocalEndpoint;
    NSXPCListenerEndpoint *_externalDeviceListenerEndpoint;
    NSArray *_distantOutputDevices;
    MRAVDistantOutputDevice *_distantGroupLeader;
}

+ (BOOL)supportsSecureCoding;
@property(retain, nonatomic) MRAVDistantOutputDevice *distantGroupLeader; // @synthesize distantGroupLeader=_distantGroupLeader;
@property(copy, nonatomic) NSArray *distantOutputDevices; // @synthesize distantOutputDevices=_distantOutputDevices;
@property(retain, nonatomic) NSXPCListenerEndpoint *externalDeviceListenerEndpoint; // @synthesize externalDeviceListenerEndpoint=_externalDeviceListenerEndpoint;
- (BOOL)isLocalEndpoint;
- (id)instanceIdentifier;
- (id)uniqueIdentifier;
@property(copy, nonatomic) NSString *localizedName;
- (id)designatedGroupLeader;
- (id)externalDevice;
- (id)outputDevices;
- (void)encodeWithCoder:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)initWithDescriptor:(id)arg1;

@end

