//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <MediaRemote/MRExternalDeviceTransport.h>

@class AVOutputContext, MRAVInputStream, MRAVOutputStream, NSArray, NSError, NSObject<OS_dispatch_queue>;

__attribute__((visibility("hidden")))
@interface MRAVOutputContextTransport : MRExternalDeviceTransport
{
    unsigned long long _state;
    NSObject<OS_dispatch_queue> *_serialQueue;
    AVOutputContext *_outputContext;
    void *_deviceInfo;
    NSError *_error;
    MRAVInputStream *_inputStream;
    MRAVOutputStream *_outputStream;
    BOOL _useSystemAuthenticationPrompt;
    NSArray *_outputDevices;
}

@property(readonly, nonatomic) NSArray *outputDevices; // @synthesize outputDevices=_outputDevices;
- (id)_onQueue_createRemoteControlContextWithID:(id)arg1;
- (void)_destroyRemoteControlContext:(id *)arg1;
- (void)_unregisterNotificationsForOutputContext:(id)arg1;
- (void)_registerNotificationsForOutputContext:(id)arg1;
- (void)_onQueue_resetStreams;
- (void)_onQueue_initializeOutputContext;
- (void)_outputContextDevicesDidChangeNotification:(id)arg1;
- (BOOL)requiresCustomPairing;
- (void)reset;
- (BOOL)getInputStream:(id *)arg1 outputStream:(id *)arg2;
- (id)error;
- (void)setShouldUseSystemAuthenticationPrompt:(BOOL)arg1;
- (BOOL)shouldUseSystemAuthenticationPrompt;
- (long long)port;
- (id)hostname;
- (id)name;
- (void *)deviceInfo;
- (id)description;
- (void)dealloc;
- (id)initWithOutputDevices:(id)arg1;

@end

