//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <MediaRemote/MRAVOutputDevice.h>

@class AVOutputDevice, MRAVOutputDeviceSourceInfo, NSData, NSDictionary, NSObject<OS_dispatch_queue>, NSString;

@interface MRAVConcreteOutputDevice : MRAVOutputDevice
{
    NSObject<OS_dispatch_queue> *_accessSerialQueue;
    AVOutputDevice *_avOutputDevice;
    MRAVOutputDeviceSourceInfo *_sourceInfo;
    NSString *_name;
    NSString *_uid;
    NSString *_modelID;
    NSString *_logicalDeviceID;
    NSString *_groupID;
    NSData *_MACAddress;
    NSDictionary *_modelSpecificInfo;
    NSString *_playingPairedDeviceName;
}

- (id)_playingPairedDeviceNameForAVOutputDevice:(id)arg1;
- (void)_onqueue_clearCachedAVOutputDeviceProperties;
- (void)setVolume:(float)arg1;
- (float)volume;
- (BOOL)isVolumeControlAvailable;
- (BOOL)requiresAuthorization;
- (BOOL)supportsExternalScreen;
- (BOOL)isLocalDevice;
- (BOOL)hasBatteryLevel;
- (float)batteryLevel;
- (unsigned int)deviceSubtype;
- (unsigned int)deviceType;
- (BOOL)isPickedOnPairedDevice;
- (BOOL)isGroupable;
- (BOOL)isGroupLeader;
- (BOOL)isRemoteControllable;
- (BOOL)canAccessRemoteAssets;
- (id)playingPairedDeviceName;
- (id)modelSpecificInfo;
- (id)MACAddress;
- (id)groupID;
- (id)modelID;
- (id)logicalDeviceID;
- (id)uid;
- (id)name;
@property(retain, nonatomic) MRAVOutputDeviceSourceInfo *sourceInfo;
@property(retain, nonatomic, setter=setAVOutputDevice:) AVOutputDevice *avOutputDevice;
- (void)dealloc;
- (id)initWithAVOutputDevice:(id)arg1 sourceInfo:(id)arg2;

@end

