//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

__attribute__((visibility("hidden")))
@interface MRContentItemRequest : NSObject <NSCoding>
{
    void *_item;
    void *_request;
}

@property(nonatomic) void *request; // @synthesize request=_request;
@property(nonatomic) void *item; // @synthesize item=_item;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (id)initWithItem:(void *)arg1 request:(void *)arg2;

@end

