//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <MediaRemote/MRProtocolMessage.h>

@interface MRGameControllerMessage : MRProtocolMessage
{
    void *_event;
    unsigned long long _priority;
}

- (BOOL)shouldLog;
- (unsigned long long)priority;
- (unsigned long long)type;
@property(readonly, nonatomic) unsigned long long controllerID;
@property(readonly, nonatomic) void *event;
- (id)initWithGameControllerEvent:(void *)arg1 controllerID:(unsigned long long)arg2;

@end

