//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <MediaRemote/MRExternalDeviceTransport.h>

@class NSNetService;

__attribute__((visibility("hidden")))
@interface MRNetServiceTransport : MRExternalDeviceTransport
{
    void *_deviceInfo;
    BOOL _requiresCustomPairing;
    NSNetService *_netService;
}

+ (void *)createDeviceInfoFromTXTRecord:(id)arg1;
+ (void *)createDeviceInfoFromNetService:(id)arg1;
@property(retain, nonatomic) NSNetService *netService; // @synthesize netService=_netService;
@property(nonatomic) BOOL requiresCustomPairing;
- (void)reset;
- (BOOL)getInputStream:(id *)arg1 outputStream:(id *)arg2;
- (id)error;
- (void)setShouldUseSystemAuthenticationPrompt:(BOOL)arg1;
- (BOOL)shouldUseSystemAuthenticationPrompt;
- (long long)port;
- (id)hostname;
- (id)name;
- (void *)deviceInfo;
- (void)updateDeviceInfoWithTXTRecord:(id)arg1;
- (id)description;
- (void)dealloc;
- (id)initWithNetService:(id)arg1;

@end

