//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MRNowPlayingClientState.h"

@class NSArray, NSMutableArray, NSObject<OS_dispatch_queue>;

@interface MRNowPlayingClient : NSObject <MRNowPlayingClientState>
{
    void *_playerPath;
    void *_client;
    NSObject<OS_dispatch_queue> *_serialQueue;
    void *_activePlayer;
    NSMutableArray *_playerClients;
}

- (id)description;
- (void)restoreNowPlayingClientState;
@property(readonly, nonatomic) NSArray *playerClients;
- (void)removePlayer:(void *)arg1;
- (id)nowPlayingPlayerClientForPlayerPath:(void *)arg1;
@property(nonatomic) void *activePlayer;
@property(nonatomic) void *client;
- (void)dealloc;
- (id)initWithPlayerPath:(void *)arg1;

@end

