//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MRNowPlayingClientState.h"

@class NSArray, NSMutableArray, NSObject<OS_dispatch_queue>;

@interface MRNowPlayingOriginClient : NSObject <MRNowPlayingClientState>
{
    void *_origin;
    NSObject<OS_dispatch_queue> *_serialQueue;
    BOOL _canBeNowPlayingApp;
    double _canBeNowPlayingAppTimestamp;
    BOOL _isOverrideApp;
    unsigned int _routeDiscoveryMode;
    NSMutableArray *_applicationPickedRoutes;
    unsigned int _inputMode;
    int _volumeCapabilities;
    CDUnknownBlockType _playbackQueueCallback;
    CDUnknownBlockType _playbackQueueTransactionCallback;
    CDUnknownBlockType _capabilitiesCallback;
    CDUnknownBlockType _commandCallback;
    CDUnknownBlockType _beginLyricsEventCallback;
    CDUnknownBlockType _endLyricsEventCallback;
    void *_activeNowPlayingClient;
    NSMutableArray *_nowPlayingClients;
    unsigned int _hardwareRemoteBehavior;
}

@property(nonatomic) unsigned int hardwareRemoteBehavior; // @synthesize hardwareRemoteBehavior=_hardwareRemoteBehavior;
@property(readonly, nonatomic) void *origin; // @synthesize origin=_origin;
- (id)description;
- (void)restoreNowPlayingClientState;
- (void)_unregisterMediaServerNotifications;
- (void)_registerMediaServerNotifications;
- (void)_avSessionMediaServicesResetNotification:(id)arg1;
- (void)removeClient:(void *)arg1;
- (id)nowPlayingClientForPlayerPath:(void *)arg1;
@property(nonatomic) void *activeNowPlayingClient;
@property(nonatomic) BOOL canBeNowPlayingApp;
@property(nonatomic) unsigned int inputMode;
@property(nonatomic) unsigned int routeDiscoveryMode;
@property(nonatomic) BOOL isOverrideApp;
@property(copy, nonatomic) NSArray *applicationPickedRoutes;
@property(copy, nonatomic) CDUnknownBlockType endLyricsEventCallback;
@property(copy, nonatomic) CDUnknownBlockType beginLyricsEventCallback;
@property(copy, nonatomic) CDUnknownBlockType commandCallback;
@property(copy, nonatomic) CDUnknownBlockType playbackQueueTransactionCallback;
@property(copy, nonatomic) CDUnknownBlockType playbackQueueCallback;
@property(readonly, nonatomic) NSArray *nowPlayingClients;
@property(nonatomic) int volumeCapabilities;
- (void)dealloc;
- (id)initWithOrigin:(void *)arg1;

@end

