//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MRNowPlayingClientState.h"

@class NSArray, NSMutableArray, NSObject<OS_dispatch_queue>;

__attribute__((visibility("hidden")))
@interface MRNowPlayingClientRequests : NSObject <MRNowPlayingClientState>
{
    void *_client;
    NSObject<OS_dispatch_queue> *_serialQueue;
    NSMutableArray *_playerClients;
    NSArray *_nowPlayingClients;
}

@property(readonly, nonatomic) NSArray *nowPlayingClients; // @synthesize nowPlayingClients=_nowPlayingClients;
@property(readonly, nonatomic) void *client; // @synthesize client=_client;
- (void)restoreNowPlayingClientState;
- (void)removePlayer:(void *)arg1;
- (id)nowPlayingPlayerClientRequestsForPlayerPath:(void *)arg1;
- (id)playerClients;
- (void)dealloc;
- (id)initWithClient:(void *)arg1;

@end

