//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>, NSOrderedSet;

@interface MRNotificationClient : NSObject
{
    unsigned long long _registeredNowPlayingObservers;
    NSObject<OS_dispatch_queue> *_nowPlayingNotificationsQueue;
    NSObject<OS_dispatch_queue> *_serialQueue;
    NSOrderedSet *_nowPlayingNotifications;
    NSOrderedSet *_routesChangedNotifications;
    NSOrderedSet *_volumeControlNotifications;
    NSOrderedSet *_externalScreenNotifications;
    NSOrderedSet *_originNotifications;
    NSOrderedSet *_supportedCommandsNotifications;
    NSOrderedSet *_voiceInputNotifications;
    NSOrderedSet *_errorNotifications;
    CDUnknownBlockType _notificationCallback;
    BOOL _receivesExternalScreenTypeChangedNotifications;
    BOOL _receivesSupportedCommandsNotifications;
    BOOL _receivesRoutesChangedNotifications;
    BOOL _receivesVolumeControlNotifications;
    BOOL _receivesOriginChangedNotifications;
    BOOL _receivesPlaybackErrorNotifications;
    BOOL _receivesVoiceInputRecordingStateNotifications;
}

+ (id)nowPlayingNotifications;
@property(nonatomic) BOOL receivesVoiceInputRecordingStateNotifications; // @synthesize receivesVoiceInputRecordingStateNotifications=_receivesVoiceInputRecordingStateNotifications;
@property(nonatomic) BOOL receivesPlaybackErrorNotifications; // @synthesize receivesPlaybackErrorNotifications=_receivesPlaybackErrorNotifications;
@property(nonatomic) BOOL receivesOriginChangedNotifications; // @synthesize receivesOriginChangedNotifications=_receivesOriginChangedNotifications;
@property(nonatomic) BOOL receivesVolumeControlNotifications; // @synthesize receivesVolumeControlNotifications=_receivesVolumeControlNotifications;
@property(nonatomic) BOOL receivesRoutesChangedNotifications; // @synthesize receivesRoutesChangedNotifications=_receivesRoutesChangedNotifications;
@property(nonatomic) BOOL receivesSupportedCommandsNotifications; // @synthesize receivesSupportedCommandsNotifications=_receivesSupportedCommandsNotifications;
@property(nonatomic) BOOL receivesExternalScreenTypeChangedNotifications; // @synthesize receivesExternalScreenTypeChangedNotifications=_receivesExternalScreenTypeChangedNotifications;
- (BOOL)postNotification:(id)arg1 userInfo:(id)arg2 object:(id)arg3;
@property(readonly, nonatomic, getter=isRegisteredForNowPlayingNotifications) BOOL registeredForNowPlayingNotifications;
- (void)unregisterForNowPlayingNotifications;
- (void)registerForNowPlayingNotificationsWithQueue:(id)arg1;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *nowPlayingNotificationQueue;
@property(copy, nonatomic) CDUnknownBlockType notificationCallback;
- (void)dealloc;
- (id)initWithNotificationCallback:(CDUnknownBlockType)arg1;

@end

