//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MRNowPlayingClientState.h"

@class NSMutableDictionary, NSObject<OS_dispatch_queue>;

@interface MRNowPlayingOriginClientManager : NSObject <MRNowPlayingClientState>
{
    NSObject<OS_dispatch_queue> *_serialQueue;
    NSMutableDictionary *_originClients;
    NSMutableDictionary *_originClientRequests;
}

+ (id)sharedManager;
- (void)removePlayer:(void *)arg1;
- (void)removeClient:(void *)arg1;
- (void)removeOrigin:(void *)arg1;
- (void)restoreNowPlayingClientState;
- (id)playerClientRequestsForPlayerPath:(void *)arg1;
- (id)clientRequestsForPlayerPath:(void *)arg1;
- (id)originClientRequestsForPlayerPath:(void *)arg1;
- (id)playerClientForPlayerPath:(void *)arg1;
- (id)clientForPlayerPath:(void *)arg1;
- (id)originClientForPlayerPath:(void *)arg1;
- (id)originClientForOrigin:(void *)arg1;
- (id)localOriginClient;
- (void)dealloc;
- (id)init;

@end

