//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MRNowPlayingClientState.h"

@class NSMutableArray, NSMutableDictionary, NSObject<OS_dispatch_queue>;

@interface MRNowPlayingOriginClientRequests : NSObject <MRNowPlayingClientState>
{
    void *_origin;
    NSObject<OS_dispatch_queue> *_serialQueue;
    NSMutableArray *_nowPlayingClients;
    NSMutableDictionary *_transactionCallbacks;
}

@property(readonly, nonatomic) void *origin; // @synthesize origin=_origin;
- (void)restoreNowPlayingClientState;
- (CDUnknownBlockType)transactionCallbackForName:(unsigned long long)arg1;
- (void)setTransactionCallback:(CDUnknownBlockType)arg1 forName:(unsigned long long)arg2;
- (void)removeClient:(void *)arg1;
- (id)nowPlayingClientRequestsForPlayerPath:(void *)arg1;
- (id)nowPlayingClients;
- (void)dealloc;
- (id)initWithOrigin:(void *)arg1;

@end

