//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSMutableSet, NSObject<OS_dispatch_queue>;

@interface MRPlaybackQueuePlayerClient : NSObject
{
    NSMutableDictionary *_cache;
    NSMutableDictionary *_offsets;
    NSMutableSet *_requests;
    void *_playerPath;
    NSObject<OS_dispatch_queue> *_queue;
}

- (id)description;
- (void)_onQueue_invalidate;
- (BOOL)verifyCommandOptions:(id)arg1 forCommand:(unsigned int)arg2;
- (void)invalidate;
- (id)subscribedContentItemsIdentifiers:(id)arg1 forRequest:(void *)arg2;
- (id)subscribedContentItems:(id)arg1 forRequest:(void *)arg2;
- (id)subscribedContentItemRequests:(id)arg1;
- (id)subscribedContentItems:(id)arg1;
- (void)subscribeToPlaybackQueue:(void *)arg1 forRequest:(void *)arg2;
- (void *)requestForContentItem:(void *)arg1;
- (id)offsetForIdentifier:(id)arg1;
- (void *)contentItemForOffset:(long long)arg1;
- (void *)nowPlayingItem;
- (void *)requestForIdentifer:(id)arg1;
- (BOOL)hasRequest:(id)arg1;
- (void)removeRequest:(id)arg1;
- (void)addRequest:(void *)arg1;
@property(readonly, nonatomic) void *playerPath;
- (id)_onQueue_writeData;
- (void)readData:(id)arg1;
- (void)dealloc;
- (id)initWithPlayerPath:(void *)arg1 queue:(id)arg2;

@end

