//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <MediaRemote/MRExternalDevice.h>

#import "MRProtocolClientConnectionDelegate.h"

@class CURunLoopThread, MRExternalClientConnection, MRExternalDeviceTransport, MRSupportedProtocolMessages, NSObject<OS_dispatch_queue>, NSString;

__attribute__((visibility("hidden")))
@interface MRTransportExternalDevice : MRExternalDevice <MRProtocolClientConnectionDelegate>
{
    NSObject<OS_dispatch_queue> *_serialQueue;
    NSObject<OS_dispatch_queue> *_workerQueue;
    CURunLoopThread *_runLoopThread;
    void *_deviceInfo;
    MRSupportedProtocolMessages *_supportedMessages;
    BOOL _wantsNowPlayingNotifications;
    BOOL _wantsNowPlayingArtworkNotifications;
    BOOL _wantsVolumeNotifications;
    BOOL _usingSystemPairing;
    unsigned int _connectionState;
    unsigned int _connectionOptions;
    void *_customOrigin;
    unsigned int _cachedServerDisconnectError;
    unsigned long long _reconnectionAttemptCount;
    BOOL _forceReconnectOnConnectionFailure;
    BOOL _disconnecting;
    BOOL _isCallingClientCallback;
    MRExternalDeviceTransport *_transport;
    MRExternalClientConnection *_connection;
    long long _connectionRecoveryBehavior;
    struct __CFData *_nowPlayingArtwork;
    struct __CFDictionary *_nowPlayingInfo;
    void *_nowPlayingItem;
    void *_playerPath;
    CDUnknownBlockType _pairingCallback;
    NSObject<OS_dispatch_queue> *_pairingCallbackQueue;
    CDUnknownBlockType _connectionStateCallback;
    NSObject<OS_dispatch_queue> *_connectionStateCallbackQueue;
    CDUnknownBlockType _nameCallback;
    NSObject<OS_dispatch_queue> *_nameCallbackQueue;
    CDUnknownBlockType _pairingAllowedCallback;
    NSObject<OS_dispatch_queue> *_pairingAllowedCallbackQueue;
    CDUnknownBlockType _customDataCallback;
    NSObject<OS_dispatch_queue> *_customDataCallbackQueue;
    CDUnknownBlockType _volumeCallback;
    NSObject<OS_dispatch_queue> *_volumeCallbackQueue;
}

@property(retain, nonatomic) NSObject<OS_dispatch_queue> *volumeCallbackQueue; // @synthesize volumeCallbackQueue=_volumeCallbackQueue;
@property(copy, nonatomic) CDUnknownBlockType volumeCallback; // @synthesize volumeCallback=_volumeCallback;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *customDataCallbackQueue; // @synthesize customDataCallbackQueue=_customDataCallbackQueue;
@property(copy, nonatomic) CDUnknownBlockType customDataCallback; // @synthesize customDataCallback=_customDataCallback;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *pairingAllowedCallbackQueue; // @synthesize pairingAllowedCallbackQueue=_pairingAllowedCallbackQueue;
@property(copy, nonatomic) CDUnknownBlockType pairingAllowedCallback; // @synthesize pairingAllowedCallback=_pairingAllowedCallback;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *nameCallbackQueue; // @synthesize nameCallbackQueue=_nameCallbackQueue;
@property(copy, nonatomic) CDUnknownBlockType nameCallback; // @synthesize nameCallback=_nameCallback;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *connectionStateCallbackQueue; // @synthesize connectionStateCallbackQueue=_connectionStateCallbackQueue;
@property(copy, nonatomic) CDUnknownBlockType connectionStateCallback; // @synthesize connectionStateCallback=_connectionStateCallback;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *pairingCallbackQueue; // @synthesize pairingCallbackQueue=_pairingCallbackQueue;
@property(copy, nonatomic) CDUnknownBlockType pairingCallback; // @synthesize pairingCallback=_pairingCallback;
@property(nonatomic) void *playerPath; // @synthesize playerPath=_playerPath;
@property(nonatomic) void *nowPlayingItem; // @synthesize nowPlayingItem=_nowPlayingItem;
@property(nonatomic) struct __CFDictionary *nowPlayingInfo; // @synthesize nowPlayingInfo=_nowPlayingInfo;
@property(nonatomic) struct __CFData *nowPlayingArtwork; // @synthesize nowPlayingArtwork=_nowPlayingArtwork;
@property(nonatomic) BOOL isCallingClientCallback; // @synthesize isCallingClientCallback=_isCallingClientCallback;
@property(nonatomic) long long connectionRecoveryBehavior; // @synthesize connectionRecoveryBehavior=_connectionRecoveryBehavior;
@property(retain, nonatomic) MRExternalClientConnection *connection; // @synthesize connection=_connection;
@property(readonly, nonatomic) MRExternalDeviceTransport *transport; // @synthesize transport=_transport;
- (void)setSupportedMessages:(id)arg1;
- (id)supportedMessages;
- (void)_contentItemUpdatedNotification:(id)arg1;
- (void *)_createPlaybackQueue:(BOOL)arg1;
- (void)_updateNowPlayingInfo;
- (void)_handleVolumeDidChangeMessage:(id)arg1;
- (void)_handleGenericMessage:(id)arg1;
- (void)_handleSetConnectionStateMessage:(id)arg1;
- (void)_handleDeviceInfoChange:(void *)arg1 oldDevice:(void *)arg2;
- (void)_handleDeviceInfoUpdateMessage:(id)arg1;
- (void)_handleTransactionMessage:(id)arg1;
- (void)_handleSetVolumeControlAvailabilityMessage:(id)arg1;
- (void)_handleNotificationMessageLegacy:(id)arg1;
- (void)_handleNotificationMessageModern:(id)arg1;
- (void)_handleNotificationMessage:(id)arg1;
- (void)_handleUpdateContentItemArtworkMessage:(id)arg1;
- (void)_handleUpdateContentItemsMessage:(id)arg1;
- (void)_handleUpdateClientMessage:(id)arg1;
- (void)_handleRemovePlayerMessage:(id)arg1;
- (void)_handleRemoveClientMessage:(id)arg1;
- (void)_handleSetNowPlayingPlayerMessage:(id)arg1;
- (void)_handleSetNowPlayingClientMessage:(id)arg1;
- (void)_handleSetArtworkMessage:(id)arg1;
- (void)_handleSetStateMessageLegacy:(id)arg1;
- (void)_handleSetStateMessageModern:(id)arg1;
- (void)_handleSetStateMessage:(id)arg1;
- (void)_handleCryptoPairingMessage:(id)arg1;
- (void)_handleRemoteCommand:(unsigned int)arg1 withOptions:(id)arg2 playerPath:(void *)arg3 completion:(CDUnknownBlockType)arg4;
- (void)_callVolumeCallback:(float)arg1 endpoint:(id)arg2 outputDevice:(id)arg3;
- (void)_callCientCustomDataCallback:(id)arg1 name:(id)arg2;
- (void)_callClientAllowsPairingCallback;
- (void)_callClientNameCallback;
- (void)_callClientPairingCallback:(CDUnknownBlockType)arg1;
- (void)_callClientConnectionStateCallback:(unsigned int)arg1 error:(id)arg2;
- (void)_handleLegacyPlaybackQueueRequestWithCompletion:(CDUnknownBlockType)arg1;
- (void)_handlePlaybackQueueResponse:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_handlePlaybackQueueRequest:(void *)arg1 forPlayer:(void *)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_registerOriginCallbacks;
- (void)_cleanUpWithReason:(long long)arg1;
- (void)_tearDownCustomOriginWithReason:(long long)arg1;
- (id)_openSecuritySession;
- (id)_loadDeviceInfo;
- (id)_setupCustomOrigin;
- (id)_initializeConnectionWithOptions:(unsigned int)arg1;
- (void)_transportDeviceInfoDidChangeNotification:(id)arg1;
- (void)_localDeviceInfoDidChangeNotification:(id)arg1;
- (void)clientDidDisconnect:(id)arg1;
- (void)clientConnection:(id)arg1 didReceiveMessage:(id)arg2;
- (void)modifyOutputContextOfType:(unsigned int)arg1 addingDeviceUIDs:(id)arg2 removingDeviceUIDs:(id)arg3 settingDeviceUIDs:(id)arg4 withReplyQueue:(id)arg5 completion:(CDUnknownBlockType)arg6;
- (void)setOutputDeviceVolume:(float)arg1 outputDevice:(id)arg2 queue:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)outputDeviceVolume:(id)arg1 queue:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)setVolume:(float)arg1 queue:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)volumeWithQueue:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)sendClientUpdatesConfigMessageWithCompletion:(CDUnknownBlockType)arg1;
- (void)sendClientUpdatesConfigMessage;
- (id)currentClientUpdatesConfigMessage;
- (id)errorForCurrentState;
- (void)ping:(double)arg1 callback:(CDUnknownBlockType)arg2 withQueue:(id)arg3;
- (void)sendCustomData:(id)arg1 withName:(id)arg2;
- (void)unpair;
- (void)disconnect:(id)arg1;
- (void)connectWithOptions:(unsigned int)arg1;
- (void)setVolumeCallback:(CDUnknownBlockType)arg1 withQueue:(id)arg2;
- (void)setCustomDataCallback:(CDUnknownBlockType)arg1 withQueue:(id)arg2;
- (void)setPairingAllowedCallback:(CDUnknownBlockType)arg1 withQueue:(id)arg2;
- (void)setNameCallback:(CDUnknownBlockType)arg1 withQueue:(id)arg2;
- (void)setConnectionStateCallback:(CDUnknownBlockType)arg1 withQueue:(id)arg2;
- (void)setPairingCallback:(CDUnknownBlockType)arg1 withQueue:(id)arg2;
- (void)setConnectionState:(unsigned int)arg1 error:(id)arg2;
- (unsigned int)connectionState;
@property(nonatomic) void *customOrigin;
- (void)setDeviceInfo:(void *)arg1;
- (void)setName:(id)arg1;
- (void)setWantsVolumeNotifications:(BOOL)arg1;
- (BOOL)wantsVolumeNotifications;
- (void)setWantsNowPlayingArtworkNotifications:(BOOL)arg1;
- (BOOL)wantsNowPlayingArtworkNotifications;
- (void)setWantsNowPlayingNotifications:(BOOL)arg1;
- (BOOL)wantsNowPlayingNotifications;
- (void)setUsingSystemPairing:(BOOL)arg1;
- (BOOL)isUsingSystemPairing;
- (BOOL)isPaired;
- (BOOL)isValid;
- (void *)deviceInfo;
- (long long)port;
- (id)hostName;
- (id)name;
@property(readonly, copy) NSString *description;
- (void)dealloc;
- (id)init;
- (id)initWithTransport:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

