//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CATTaskClientDelegate.h"

@class CATOperationQueue, CATTaskClient, NSString;

@interface DMFConnection : NSObject <CATTaskClientDelegate>
{
    BOOL _isConnected;
    CATTaskClient *_taskClient;
    CATOperationQueue *_operationQueue;
}

+ (id)watchOSRequestClasses;
+ (id)tvOSRequestClasses;
+ (id)macOSRequestClasses;
+ (id)iOSRequestClasses;
+ (id)currentPlatformRequestClasses;
+ (id)sharedConnection;
@property(nonatomic) BOOL isConnected; // @synthesize isConnected=_isConnected;
@property(retain, nonatomic) CATOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
@property(retain, nonatomic) CATTaskClient *taskClient; // @synthesize taskClient=_taskClient;
- (void).cxx_destruct;
- (void)operationDidFinish:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)client:(id)arg1 didInterruptWithError:(id)arg2;
- (void)client:(id)arg1 didDisconnectWithError:(id)arg2;
- (void)clientDidInvalidate:(id)arg1;
- (void)clientDidConnect:(id)arg1;
- (void)invalidate;
- (id)progressForAllInflightRequests;
- (id)prepareOperationForRequest:(id)arg1;
- (void)performRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)dealloc;
- (id)initWithTransport:(id)arg1;
- (id)initWithXPCConnection:(id)arg1;
- (id)initWithServiceName:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

