//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CATTaskResultObject.h"

@class DMFOSUpdateInformation, NSNumber;

@interface DMFFetchOSUpdateStatusResultObject : CATTaskResultObject
{
    BOOL _isDownloading;
    BOOL _isDownloaded;
    BOOL _isInstalling;
    DMFOSUpdateInformation *_updateInformation;
    NSNumber *_downloadPercentComplete;
}

+ (BOOL)supportsSecureCoding;
@property(nonatomic) BOOL isInstalling; // @synthesize isInstalling=_isInstalling;
@property(nonatomic) BOOL isDownloaded; // @synthesize isDownloaded=_isDownloaded;
@property(nonatomic) BOOL isDownloading; // @synthesize isDownloading=_isDownloading;
@property(copy, nonatomic) NSNumber *downloadPercentComplete; // @synthesize downloadPercentComplete=_downloadPercentComplete;
@property(copy, nonatomic) DMFOSUpdateInformation *updateInformation; // @synthesize updateInformation=_updateInformation;
- (void).cxx_destruct;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithUpdateInformation:(id)arg1 downloadPercentComplete:(id)arg2 isDownloading:(BOOL)arg3 isDownloaded:(BOOL)arg4 isInstalling:(BOOL)arg5;

@end

