//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "NSSecureCoding.h"

@interface DMFSecurityInformation : NSObject <NSCopying, NSSecureCoding>
{
    BOOL _supportsBlockLevelEncryption;
    BOOL _supportsFileLevelEncryption;
    BOOL _passcodeIsSet;
    BOOL _passcodeIsCompliantWithGlobalRestrictions;
    BOOL _passcodeIsCompliantWithProfileRestrictions;
    BOOL _passcodeLockGracePeriodIsEnforced;
    double _passcodeLockGracePeriodSeconds;
}

+ (BOOL)supportsSecureCoding;
@property(nonatomic) double passcodeLockGracePeriodSeconds; // @synthesize passcodeLockGracePeriodSeconds=_passcodeLockGracePeriodSeconds;
@property(nonatomic) BOOL passcodeLockGracePeriodIsEnforced; // @synthesize passcodeLockGracePeriodIsEnforced=_passcodeLockGracePeriodIsEnforced;
@property(nonatomic) BOOL passcodeIsCompliantWithProfileRestrictions; // @synthesize passcodeIsCompliantWithProfileRestrictions=_passcodeIsCompliantWithProfileRestrictions;
@property(nonatomic) BOOL passcodeIsCompliantWithGlobalRestrictions; // @synthesize passcodeIsCompliantWithGlobalRestrictions=_passcodeIsCompliantWithGlobalRestrictions;
@property(nonatomic) BOOL passcodeIsSet; // @synthesize passcodeIsSet=_passcodeIsSet;
@property(nonatomic) BOOL supportsFileLevelEncryption; // @synthesize supportsFileLevelEncryption=_supportsFileLevelEncryption;
@property(nonatomic) BOOL supportsBlockLevelEncryption; // @synthesize supportsBlockLevelEncryption=_supportsBlockLevelEncryption;
- (id)description;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithSupportsBlockLevelEncryption:(BOOL)arg1 supportsFileLevelEncryption:(BOOL)arg2 passcodeIsSet:(BOOL)arg3 passcodeIsCompliantWithGlobalRestrictions:(BOOL)arg4 passcodeIsCompliantWithProfileRestrictions:(BOOL)arg5 passcodeLockGracePeriodIsEnforced:(BOOL)arg6 passcodeLockGracePeriodSeconds:(double)arg7;

@end

