//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CATTaskResultObject.h"

@class DMFOSUpdateInformation;

@interface DMFScheduleOSUpdateResultObject : CATTaskResultObject
{
    unsigned long long _action;
    DMFOSUpdateInformation *_information;
}

+ (BOOL)supportsSecureCoding;
@property(retain, nonatomic) DMFOSUpdateInformation *information; // @synthesize information=_information;
@property(nonatomic) unsigned long long action; // @synthesize action=_action;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithAction:(unsigned long long)arg1 information:(id)arg2;

@end

