//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSUUID;

@interface WRM_iRATProximityRecommendationLogging : NSObject
{
    NSUUID *_Uuid;
    unsigned long long _btRSSI;
    long long _wifiRSSI;
    long long _wifiSNR;
    long long _lsmRecommendationBe;
    long long _lsmRecommendationVoice;
    long long _expectedThroughputVIBE;
    long long _expectedThroughputVO;
    long long _packetLifetimeVIBE;
    long long _pkgLifeTimeVO;
    long long _pktLossRateVO;
}

@property(nonatomic) long long pktLossRateVO; // @synthesize pktLossRateVO=_pktLossRateVO;
@property(nonatomic) long long pkgLifeTimeVO; // @synthesize pkgLifeTimeVO=_pkgLifeTimeVO;
@property(nonatomic) long long packetLifetimeVIBE; // @synthesize packetLifetimeVIBE=_packetLifetimeVIBE;
@property(nonatomic) long long expectedThroughputVO; // @synthesize expectedThroughputVO=_expectedThroughputVO;
@property(nonatomic) long long expectedThroughputVIBE; // @synthesize expectedThroughputVIBE=_expectedThroughputVIBE;
@property(nonatomic) long long lsmRecommendationVoice; // @synthesize lsmRecommendationVoice=_lsmRecommendationVoice;
@property(nonatomic) long long lsmRecommendationBe; // @synthesize lsmRecommendationBe=_lsmRecommendationBe;
@property(nonatomic) long long wifiSNR; // @synthesize wifiSNR=_wifiSNR;
@property(nonatomic) long long wifiRSSI; // @synthesize wifiRSSI=_wifiRSSI;
@property(nonatomic) unsigned long long btRSSI; // @synthesize btRSSI=_btRSSI;
@property(retain, nonatomic) NSUUID *Uuid; // @synthesize Uuid=_Uuid;
- (void)dealloc;
- (id)init;

@end

