//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface SidecarMenuObserver : NSObject
{
}

+ (id)defaultObserver;
- (void)_sidecarInsertAction:(id)arg1;
- (void)_sidecarImportAction:(id)arg1;
- (void)_sidecarPhotosBrowser:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;

@end

