//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SOCloudKitAlertController : NSObject
{
    BOOL _isPrompting;
}

+ (id)sharedInstance;
+ (void)__setSingleton__im:(id)arg1;
+ (id)__singleton__im;
@property(nonatomic) BOOL isPrompting; // @synthesize isPrompting=_isPrompting;
- (void)promptWithModalSheetInWindow:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)_promptDidCompleteWithModalResponse:(long long)arg1 inWindow:(id)arg2;
- (void)_presentAlertInWindow:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) BOOL canPrompt;
@property(nonatomic) BOOL didPrompt;

@end

