//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IMCloudKitSyncState, IMCloudKitSyncStatistics, NSArray, NSString;

@interface IMCloudKitSyncProgress : NSObject
{
    BOOL _hidden;
    BOOL _shouldShowProgressBar;
    BOOL _finishing;
    NSString *_progressLabel;
    double _progressBarValue;
    double _progressBarMax;
    NSString *_userMessageLabel;
    NSString *_actionLabel;
    long long _actionType;
    IMCloudKitSyncState *_syncState;
    IMCloudKitSyncStatistics *_syncStatistics;
}

+ (id)createSyncProgressWithSyncState:(id)arg1 syncStatistics:(id)arg2 finishing:(BOOL)arg3 hidden:(BOOL)arg4;
@property(readonly, nonatomic, getter=isFinishing) BOOL finishing; // @synthesize finishing=_finishing;
@property(nonatomic) BOOL shouldShowProgressBar; // @synthesize shouldShowProgressBar=_shouldShowProgressBar;
@property(readonly, nonatomic) IMCloudKitSyncStatistics *syncStatistics; // @synthesize syncStatistics=_syncStatistics;
@property(readonly, nonatomic) IMCloudKitSyncState *syncState; // @synthesize syncState=_syncState;
@property(nonatomic) long long actionType; // @synthesize actionType=_actionType;
@property(retain, nonatomic) NSString *actionLabel; // @synthesize actionLabel=_actionLabel;
@property(retain, nonatomic) NSString *userMessageLabel; // @synthesize userMessageLabel=_userMessageLabel;
@property(nonatomic) double progressBarMax; // @synthesize progressBarMax=_progressBarMax;
@property(nonatomic) double progressBarValue; // @synthesize progressBarValue=_progressBarValue;
@property(retain, nonatomic) NSString *progressLabel; // @synthesize progressLabel=_progressLabel;
@property(nonatomic, getter=isHidden) BOOL hidden; // @synthesize hidden=_hidden;
- (void).cxx_destruct;
@property(readonly, nonatomic) BOOL shouldShowUserMessageLabel; // @dynamic shouldShowUserMessageLabel;
@property(readonly, nonatomic) BOOL shouldShowUserActionLabel; // @dynamic shouldShowUserActionLabel;
@property(readonly, nonatomic) NSArray *errors; // @dynamic errors;
@property(readonly, nonatomic) double remainingItems; // @dynamic remainingItems;
@property(readonly, nonatomic) double percentComplete; // @dynamic percentComplete;
- (id)description;
- (void)updateState;
@property(readonly, nonatomic) NSString *percentCompleteString; // @dynamic percentCompleteString;
- (id)initWithSyncState:(id)arg1 syncStatistics:(id)arg2 finishing:(BOOL)arg3 hidden:(BOOL)arg4;

@end

