//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IMCloudKitHooks : NSObject
{
}

+ (id)sharedInstance;
+ (void)__setSingleton__im:(id)arg1;
+ (id)__singleton__im;
- (void)fetchCloudKitSyncStateDebuggingInfo:(id)arg1;
- (id)syncStateDictionary;
- (id)lastSyncErrors;
- (void)syncDeletesToCloudKit;
- (void)printCachedRampState;
- (void)fetchLatestRampState;
- (void)writeCloudKitSyncCounts:(id)arg1;
- (void)fetchSyncStateStatistics;
- (void)purgeAttachments:(long long)arg1;
- (void)metricAttachments:(long long)arg1;
- (void)deleteSalt;
- (void)printCachedSalt;
- (void)fetchLatestSalt;
- (void)clearTombStoneMessagesTable;
- (void)loadDeletedMessagesWithLimit:(long long)arg1;
- (void)_updateCloudKitState;
- (void)_updateCloudKitStateWithDictionary:(id)arg1;
- (BOOL)isInExitState;
- (void)_didAttemptToDisableAllDevicesResult:(_Bool)arg1;
- (BOOL)isDisablingDevices;
- (void)_didPerformAdditionalStorageRequiredCheckWithSuccess:(BOOL)arg1 additionalStorageRequired:(unsigned long long)arg2 forAccountId:(id)arg3 error:(id)arg4;
- (long long)isChangingEnabledState;
- (void)_didAttemptToSetEnabledTo:(BOOL)arg1 result:(_Bool)arg2;
- (id)lastSyncDate;
- (BOOL)isSyncing;
- (BOOL)isStartingSync;
- (void)initiateSync;
- (void)setShouldOptimizeAttachmentStorage:(BOOL)arg1;
- (BOOL)shouldOptimizeAttachmentStorage;
- (BOOL)eligibleForTruthZone;
- (BOOL)rampedIntoTruthZone;
- (BOOL)removedFromiCloudBackup;
- (void)tryToDisableAllDevices;
- (void)performAdditionalStorageRequiredCheck;
- (void)setEnabled:(BOOL)arg1;
- (BOOL)isEnabled;
- (BOOL)shouldShowCloudKitUI;
- (void)clearDataFromCloudKit;
- (void)clearLocalSyncState;
- (void)loadDirtyMessagesWithLimit:(long long)arg1;
- (void)initiatePeriodicSync;
- (void)downloadAttachmentAssets;
- (void)syncMessages;
- (void)deleteExitRecord;
- (void)fetchExitRecord;
- (void)writeExitRecord;
- (void)deleteMessagesZone;
- (void)writeDirtyMessages;
- (void)deleteAttachmentZone;
- (void)syncAttachments;
- (void)writeAttachments;
- (void)createAttachmentZone;
- (void)clearChatZoneSyncToken;
- (void)markAllChatsAsDirty;
- (void)syncChats;
- (void)deleteChatZone;
- (void)writeDirtyChats;
- (void)createChatZone;
- (void)setupIMCloudKitHooks;
- (id)init;

@end

