//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate;

@interface IMCloudKitMockSyncState : NSObject
{
    BOOL _IMCloudKitSyncingEnabled;
    BOOL _IMCloudKitIsSyncing;
    BOOL _IMCloudKitIsRampedIntoTruthZone;
    BOOL _IMCloudKitIsEligibleForTruthZone;
    BOOL _IMCloudKitIsInExitState;
    BOOL _IMCloudKitIsRemovedFromBackup;
    BOOL _IMCloudKitStartingPeriodicSync;
    BOOL _IMCloudKitStartingInitialSync;
    BOOL _IMCloudKitStartingDisableDevices;
    NSDate *_IMCloudKitSyncDate;
    long long _IMCloudKitStartingEnabledSettingChange;
    unsigned long long _IMCKSyncControllerSyncState;
    unsigned long long _IMCKSyncControllerSyncType;
}

@property unsigned long long IMCKSyncControllerSyncType; // @synthesize IMCKSyncControllerSyncType=_IMCKSyncControllerSyncType;
@property unsigned long long IMCKSyncControllerSyncState; // @synthesize IMCKSyncControllerSyncState=_IMCKSyncControllerSyncState;
@property BOOL IMCloudKitStartingDisableDevices; // @synthesize IMCloudKitStartingDisableDevices=_IMCloudKitStartingDisableDevices;
@property long long IMCloudKitStartingEnabledSettingChange; // @synthesize IMCloudKitStartingEnabledSettingChange=_IMCloudKitStartingEnabledSettingChange;
@property BOOL IMCloudKitStartingInitialSync; // @synthesize IMCloudKitStartingInitialSync=_IMCloudKitStartingInitialSync;
@property BOOL IMCloudKitStartingPeriodicSync; // @synthesize IMCloudKitStartingPeriodicSync=_IMCloudKitStartingPeriodicSync;
@property(retain) NSDate *IMCloudKitSyncDate; // @synthesize IMCloudKitSyncDate=_IMCloudKitSyncDate;
@property BOOL IMCloudKitIsRemovedFromBackup; // @synthesize IMCloudKitIsRemovedFromBackup=_IMCloudKitIsRemovedFromBackup;
@property BOOL IMCloudKitIsInExitState; // @synthesize IMCloudKitIsInExitState=_IMCloudKitIsInExitState;
@property BOOL IMCloudKitIsEligibleForTruthZone; // @synthesize IMCloudKitIsEligibleForTruthZone=_IMCloudKitIsEligibleForTruthZone;
@property BOOL IMCloudKitIsRampedIntoTruthZone; // @synthesize IMCloudKitIsRampedIntoTruthZone=_IMCloudKitIsRampedIntoTruthZone;
@property BOOL IMCloudKitIsSyncing; // @synthesize IMCloudKitIsSyncing=_IMCloudKitIsSyncing;
@property BOOL IMCloudKitSyncingEnabled; // @synthesize IMCloudKitSyncingEnabled=_IMCloudKitSyncingEnabled;
- (void).cxx_destruct;
- (id)convertToDictionary;

@end

