//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <IMCore/IMCloudKitEventNotificationTest.h>

@interface IMCloudKitSyncingProgressTest : IMCloudKitEventNotificationTest
{
    int _count;
    int _counter;
    unsigned long long _syncState;
    unsigned long long _syncType;
}

- (void)startTest;
- (void)next;
- (id)initWithSyncState:(unsigned long long)arg1 syncType:(unsigned long long)arg2;

@end

