//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMSingletonOverride.h"

@class IMCloudKitMockSyncState, NSArray, NSDate, NSDictionary;

@interface IMCloudKitHookTestSingleton : IMSingletonOverride
{
    IMCloudKitMockSyncState *_testState;
    BOOL _isStartingSync;
    BOOL _isDisablingDevices;
    NSArray *_lastSyncErrors;
    long long _isChangingEnabledState;
    NSDictionary *_syncStats;
}

@property(retain, nonatomic) NSDictionary *syncStats; // @synthesize syncStats=_syncStats;
@property(nonatomic) BOOL isDisablingDevices; // @synthesize isDisablingDevices=_isDisablingDevices;
@property(nonatomic) BOOL isStartingSync; // @synthesize isStartingSync=_isStartingSync;
@property(nonatomic) long long isChangingEnabledState; // @synthesize isChangingEnabledState=_isChangingEnabledState;
@property(retain, nonatomic) NSArray *lastSyncErrors; // @synthesize lastSyncErrors=_lastSyncErrors;
@property(retain, nonatomic) IMCloudKitMockSyncState *testState; // @synthesize testState=_testState;
- (void).cxx_destruct;
@property(nonatomic) unsigned long long controllerSyncType;
@property(nonatomic) unsigned long long controllerSyncState;
- (void)setIsInExitState:(BOOL)arg1;
- (BOOL)isInExitState;
- (id)syncStateDictionary;
@property(retain, nonatomic) NSDate *lastSyncDate;
- (void)initiatePeriodicSync;
@property(nonatomic, getter=isSyncing) BOOL syncing;
@property(nonatomic) BOOL eligibleForTruthZone;
@property(nonatomic) BOOL rampedIntoTruthZone;
@property(nonatomic, getter=isEnabled) BOOL enabled;
- (void)sendSyncChangedEvent;
- (void)fetchSyncStateStatistics;
- (id)init;

@end

