//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <IMCore/IMCloudKitSyncProgress.h>

@interface IMCloudKitSyncProgressErrorOccurred : IMCloudKitSyncProgress
{
}

- (void)updateState;
- (BOOL)_setLabelsIfKnownError:(id)arg1;

@end

