//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSString;

@interface IMSPIRecentEvent : NSObject
{
    NSString *_handle;
    NSDate *_date;
}

@property(retain) NSDate *date; // @synthesize date=_date;
@property(retain) NSString *handle; // @synthesize handle=_handle;
- (void).cxx_destruct;
- (id)description;
- (id)initWithHandle:(id)arg1 date:(id)arg2;

@end

