//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface APCCodecFactory : NSObject
{
}

+ (float)evaluateCarrierWithConfig:(id)arg1 carrier:(id)arg2 carrierOffset:(unsigned long long *)arg3;
+ (unique_ptr_5bd60e54)createEncoderWithConfig:(id)arg1 apcConfig:(map_8903fe1c *)arg2 payloadData:(id)arg3;
+ (unique_ptr_36d0a635)createDecoderWithConfig:(id)arg1 apcConfig:(map_8903fe1c *)arg2;

@end

