//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TUCoreTelephonyClient.h"

@class NSString;

@protocol TUEmergencyCoreTelephonyClient <TUCoreTelephonyClient>
- (BOOL)shouldShowEmergencyCallbackModeAlertForSubscriptionLabelID:(NSString *)arg1 error:(id *)arg2;
- (BOOL)isWhitelistedEmergencyNumberForDigits:(NSString *)arg1 subscriptionLabelID:(NSString *)arg2 error:(id *)arg3;
- (BOOL)isWhitelistedEmergencyNumberForDigits:(NSString *)arg1 subscription:(id <TUTelephonySubscription>)arg2 error:(id *)arg3;
- (BOOL)isEmergencyNumberForDigits:(NSString *)arg1 subscriptionLabelID:(NSString *)arg2 error:(id *)arg3;
- (BOOL)isEmergencyNumberForDigits:(NSString *)arg1 subscription:(id <TUTelephonySubscription>)arg2 error:(id *)arg3;
@end

