//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "NSSecureCoding.h"

@class NSSet, NSURL, NSUUID;

@interface TUJoinConversationRequest : NSObject <NSCopying, NSSecureCoding>
{
    BOOL _videoEnabled;
    BOOL _shouldSuppressInCallUI;
    BOOL _wantsStagingArea;
    NSSet *_remoteMembers;
    NSUUID *_UUID;
    NSUUID *_messagesGroupUUID;
}

+ (BOOL)supportsSecureCoding;
+ (id)messagesGroupUUIDFromURLComponents:(id)arg1;
+ (BOOL)wantsStagingAreaFromURLComponents:(id)arg1;
+ (BOOL)shouldSuppressInCallUIFromURLComponents:(id)arg1;
+ (BOOL)videoEnabledFromURLComponents:(id)arg1;
+ (id)remoteMembersFromURLComponents:(id)arg1;
@property(copy, nonatomic) NSUUID *messagesGroupUUID; // @synthesize messagesGroupUUID=_messagesGroupUUID;
@property(nonatomic) BOOL wantsStagingArea; // @synthesize wantsStagingArea=_wantsStagingArea;
@property(nonatomic) BOOL shouldSuppressInCallUI; // @synthesize shouldSuppressInCallUI=_shouldSuppressInCallUI;
@property(nonatomic, getter=isVideoEnabled) BOOL videoEnabled; // @synthesize videoEnabled=_videoEnabled;
@property(retain, nonatomic) NSUUID *UUID; // @synthesize UUID=_UUID;
@property(readonly, copy, nonatomic) NSSet *remoteMembers; // @synthesize remoteMembers=_remoteMembers;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)messagesGroupUUIDQueryItem;
- (id)wantsStagingAreaQueryItem;
- (id)shouldSuppressInCallUIQueryItem;
- (id)videoEnabledQueryItem;
- (id)remoteMembersQueryItem;
- (id)queryItems;
@property(readonly, nonatomic) NSURL *URL;
- (id)description;
- (id)initWithGroupUUID:(id)arg1 localParticipantHandle:(id)arg2 remoteParticipantHandles:(id)arg3;
- (id)initWithURL:(id)arg1;
- (id)initWithConversation:(id)arg1;
- (id)initWithRemoteMembers:(id)arg1;

@end

