//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableData;

@interface HDRBackwardDisplayManagement : NSObject
{
    unsigned long long _frameIndex;
    id <MTLDeviceSPI> _device;
    id <MTLLibrary> _defaultLibrary;
    id <MTLRenderPipelineState> _BKDM_ARGB_Linear;
    id <MTLRenderPipelineState> _BKDM_ARGB_Gamma;
    id <MTLRenderPipelineState> _BKDM_3Plane_2Pixel_Linear[4];
    id <MTLRenderPipelineState> _BKDM_3Plane_1Pixel_Linear[4];
    id <MTLRenderPipelineState> _BKDM_3Plane_1Pixel_Gamma[4];
    id <MTLRenderPipelineState> _BKDM_3Plane_1Pixel_Gamma_Scaled[4];
    id <MTLRenderPipelineState> _BKDM_3Plane_1Pixel_Video_Scaled[4];
    id <MTLRenderPipelineState> _BKDM_3Plane_2Pixel_Gamma_Scaled[4];
    id <MTLRenderPipelineState> _BKDM_3Plane_2Pixel_Video_Scaled[4];
    id <MTLRenderPipelineState> _BKDM_SDROnly[4];
    id <MTLRenderPipelineState> _BKDM_SDRBlending[4];
    id <MTLRenderPipelineState> _colorfill1[4];
    id <MTLRenderPipelineState> _colorfill2[4];
    id <MTLRenderPipelineState> _fillUI1[4];
    id <MTLRenderPipelineState> _fillUI1SDR[4];
    id <MTLRenderPipelineState> _fillUI2[4];
    id <MTLRenderPipelineState> _metadataKernel;
    id <MTLRenderPipelineState> _metadataKernel2Pixel;
    id <MTLSamplerState> _inputSampler;
    id <MTLTexture> _pq2LTable;
    id <MTLTexture> _l2PQTable;
    id <MTLTexture> _degammaTable;
    id <MTLTexture> _inverseScalingFactorTableTexture;
    id <MTLTexture> _inverseScalingFactorTableTextures[3];
    NSMutableData *_inverseScalingTable;
    id <MTLTexture> _sdrScalingFactorTableTexture;
    id <MTLTexture> _yuvScalingFactorTableTexture;
    NSMutableData *_sdrScalingTable;
    NSMutableData *_yuvScalingTable;
    float _cached_target_white;
    float _cached_target_black;
    float _cached_source_white;
    float _cached_source_black;
    float _cached_satBoost;
    BOOL _cached_SDR_status;
    float _prev_SlopeScaled;
    float _prev_c1;
    float _prev_c2;
    float _prev_c3;
    NSMutableData *_degammaHalfTable;
    float _prev_maxHalfRGBValue;
    id <MTLBuffer> _uniformBuffer;
    id <MTLBuffer> _uniformBuffers[3];
    id <MTLBuffer> _vertsBuffer;
    id <MTLBuffer> _vertsBuf;
    id <MTLBuffer> _vertsBufs[3];
    int _num_Video_Rects;
    int _num_UI_Rects;
    CDStruct_8e61eb45 _cachedFullRegion;
    CDStruct_8e61eb45 _cachedVideoDstRegion[3];
    CDStruct_8e61eb45 _cachedVideoSrcRegion[3];
    id <MTLBuffer> _metadataVertexBuffer;
    int _metadataSpanCount[2];
    int _width;
    int _height;
    int _targetWidth;
    int _targetHeight;
    id <MTLTexture> _metadataTexture[2];
    id <MTLTexture> _metadataTextures[3][2];
    id <MTLTexture> _inputTexture[3];
    id <MTLTexture> _outputTexture;
    id <MTLTexture> _outputTextureMetadata;
    id <MTLTexture> _intermediateTexture;
    id <MTLTexture> _uiTexture;
    float _inputScaleFactor;
    unsigned int _displayMaxBrightnessInNits;
    float _displayMinBrightnessInNits;
    BOOL _hasDisplayBrightnessFromEDID;
    unsigned int _outputPackingColorFormat;
    unsigned long long _totalInverseScalingTableTime;
    unsigned int _inverseScalingTableIndex;
    unsigned int _maxFillInverseScalingTableTime;
    unsigned int _minFillInverseScalingTableTime;
    BOOL _useAccessibilityMatrix;
    CDStruct_e50908d0 _cachedHDRMatrix;
}

- (void).cxx_destruct;
- (void)attatchInfoFrame:(CDStruct_bd0e21b1 *)arg1 toOutputSurface:(struct __IOSurface *)arg2;
- (id)createRenderCommandEncoderWithCommandBuffer:(id)arg1 texture:(id)arg2 widthScale:(unsigned int)arg3 loadAction:(unsigned long long)arg4;
- (void)setupMetadataTextureWithOutput:(struct __IOSurface *)arg1;
- (void)setupTexturesWithInput:(struct __IOSurface *)arg1 VideoSRGB:(BOOL)arg2 UI:(struct __IOSurface *)arg3 UISRGB:(BOOL)arg4 Output:(struct __IOSurface *)arg5 PixelPerThread:(int)arg6;
- (int)pixelNumPerThreadFullScreen:(BOOL)arg1 videoInput:(struct __IOSurface *)arg2 UI:(struct __IOSurface *)arg3 Output:(struct __IOSurface *)arg4;
- (long long)encodeToCommandBuffer:(id)arg1 video:(struct __IOSurface *)arg2 videoSrcRegion:(CDStruct_8e61eb45)arg3 videoDstRegion:(CDStruct_8e61eb45)arg4 ui:(struct __IOSurface *)arg5 uiSrcRegion:(CDStruct_8e61eb45)arg6 uiDstRegion:(CDStruct_8e61eb45)arg7 backgroundColor:(CDStruct_d2b197d1 *)arg8 output:(struct __IOSurface *)arg9 frameProperties:(id)arg10;
- (long long)setAccessibilityMatrix:(CDStruct_e50908d0 *)arg1;
- (long long)encodeToCommandBuffer:(id)arg1 video:(struct __IOSurface *)arg2 videoSrcRegion:(CDStruct_8e61eb45)arg3 videoDstRegion:(CDStruct_8e61eb45)arg4 ui:(struct __IOSurface *)arg5 output:(struct __IOSurface *)arg6 frameProperties:(id)arg7;
- (long long)encodeToCommandBuffer:(id)arg1 video:(struct __IOSurface *)arg2 ui:(struct __IOSurface *)arg3 output:(struct __IOSurface *)arg4 frameProperties:(id)arg5;
- (long long)EncodeToCommandBuffer:(id)arg1 inputSurface:(struct __IOSurface *)arg2 uiSurface:(struct __IOSurface *)arg3 outputSurface:(struct __IOSurface *)arg4 frameProperties:(id)arg5;
- (long long)encodeToCommandBuffer:(id)arg1 inputSurface:(struct __IOSurface *)arg2 outputSurface:(struct __IOSurface *)arg3 frameProperties:(id)arg4;
- (void)packetizeMetadata:(CDStruct_5ad502c8 *)arg1 length:(int)arg2 into:(int)arg3 onSurface:(struct __IOSurface *)arg4;
- (int)getTVIndex;
- (void)handleMetaInsertion:(BOOL)arg1 encoder:(id)arg2 widthScale:(int)arg3 payloadLength:(unsigned int)arg4;
- (void)drawMetaWithEncoder:(id)arg1 widthScale:(int)arg2 dmPayLoadLength:(int)arg3;
- (void)generateMetaAndConfig:(id)arg1 inputSurface:(struct __IOSurface *)arg2 outputSurface:(struct __IOSurface *)arg3 payLoad:(struct **)arg4 payloadLength:(unsigned int *)arg5 dmCfg:(struct **)arg6;
- (BOOL)updateConfigFromMetadata:(CDStruct_bd0e21b1 *)arg1 uiScaleFactor:(float)arg2 width:(int)arg3 background:(CDStruct_d2b197d1 *)arg4 hdrVideoOnly:(BOOL)arg5 hdr10TV:(BOOL)arg6;
- (void)updateVertices:(CDStruct_8e61eb45)arg1 videoDstRegion:(CDStruct_8e61eb45)arg2 videoSrcRegion:(CDStruct_8e61eb45)arg3 dstWidth:(int)arg4 dstHeight:(int)arg5 videoSrcWidth:(int)arg6 videoSrcHeight:(int)arg7 index:(int)arg8 scale:(int)arg9;
- (void)createMetadataVertexBuffer;
- (void)createMetadataTexture;
- (void)createBuffers;
- (void)reportLutStatics;
- (void)fillDegammaTable:(float)arg1;
- (void)fillScalingTable_YUVTM:(CDStruct_bd0e21b1 *)arg1 satBoost:(float)arg2 scalingFactor:(BOOL)arg3 sdrOnly:(BOOL)arg4 clampNoiseToBlack:(BOOL)arg5;
- (void)fillScalingTable_SDR2HDR:(CDStruct_bd0e21b1 *)arg1 target_White:(float)arg2 target_Black:(float)arg3 clampNoiseToBlack:(BOOL)arg4;
- (void)fillInverseScalingFactorTableFromDMConfig:(CDStruct_bd0e21b1 *)arg1;
- (void)createDegammaTable;
- (void)createYUVScalingFactorTable;
- (void)createSDRScalingFactorTable;
- (void)createInverseScalingFactorTable;
- (void)createL2PQTable;
- (void)createPQ2LTable;
- (void)createSamplers;
- (void)createKernels;
- (id)createRenderPipeLineWithVertexName:(id)arg1 fragmentName:(id)arg2 colorFormat:(unsigned long long)arg3 useCustomMatrix:(BOOL)arg4;
- (void)setupMetal;
- (unsigned int)getPackagingColorFormatFromDictionary:(id)arg1 withDefaultValue:(unsigned int)arg2;
- (void)initDisplayAttributes:(id)arg1;
- (void)initWithDevice:(id)arg1;
- (id)initWithDevice:(id)arg1 displayProperties:(id)arg2;

@end

