//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <OSAnalytics/PCCEndpoint.h>

@class NSObject<OS_dispatch_queue>, OS_xpc_remote_connection;

@interface PCCBridgeEndpoint : PCCEndpoint
{
    NSObject<OS_dispatch_queue> *_eventQueue;
    OS_xpc_remote_connection *_remoteConnection;
    OS_xpc_remote_connection *_listeningConnection;
    BOOL _interruptedState;
}

+ (BOOL)isBridgePresent;
- (void).cxx_destruct;
- (void)_forceConnection;
- (id)send:(id)arg1 file:(id)arg2 metadata:(id)arg3 error:(id *)arg4;
- (id)send:(id)arg1 message:(id)arg2 error:(id *)arg3;
- (BOOL)isDeviceNearby:(id)arg1;
- (void)onDeviceDisconnected:(id)arg1;
- (void)onDeviceConnected:(id)arg1;
- (void)outreach;
- (id)deviceIds;
- (void)dealloc;
- (id)init;

@end

