//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString, PCCEndpoint;

@interface PCCProxiedDevice : NSObject
{
    PCCEndpoint *_endpoint;
    NSObject<OS_dispatch_queue> *_serial_list_queue;
    NSString *_jobId;
    NSString *_jobTarget;
    BOOL _jobSpecificLogXferMode;
    NSMutableArray *_log_sets;
    NSMutableDictionary *_pending_list;
    unsigned int _total_count;
    unsigned int _rejected_count;
    unsigned int _success_count;
    unsigned int _error_count;
    unsigned int _consecutive_error_count;
    BOOL _preserveFiles;
}

@property BOOL preserveFiles; // @synthesize preserveFiles=_preserveFiles;
- (void).cxx_destruct;
- (void)finishJob:(id)arg1 error:(id)arg2;
- (void)initiate:(id)arg1 transferLog:(id)arg2 job:(id)arg3;
- (void)initiate:(id)arg1 transferGroupWithOptions:(id)arg2 job:(id)arg3;
- (void)ack:(id)arg1 result:(BOOL)arg2 error:(id)arg3;
- (void)sendNextLog;
- (void)runCrashMoverService:(id)arg1;
- (void)acceptTaskingPayload:(id)arg1 forRouting:(id)arg2 withId:(id)arg3 digest:(id)arg4;
- (void)sendDeviceMetadata:(id)arg1;
- (void)handleMessage:(id)arg1 from:(id)arg2;
- (void)handleConnection:(BOOL)arg1;
- (void)sweepLogs;
- (void)explore;
- (id)initWithEndpoint:(id)arg1;

@end

