//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSExtension, NSObject<OS_dispatch_queue>;

@interface ILClassificationController : NSObject
{
    NSExtension *_electedExtension;
    NSArray *_extensions;
    NSObject<OS_dispatch_queue> *_queue;
}

+ (id)electedExtensionFromExtensions:(id)arg1;
+ (id)sharedInstance;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(copy, nonatomic) NSArray *extensions; // @synthesize extensions=_extensions;
- (void).cxx_destruct;
@property(copy, nonatomic) NSExtension *electedExtension; // @synthesize electedExtension=_electedExtension;
@property(readonly, nonatomic, getter=isClassificationAvailable) BOOL classificationAvailable;
- (void)updateExtensions:(id)arg1;
- (void)activateWithCompletion:(CDUnknownBlockType)arg1;
- (id)init;

@end

