//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SFProximityEstimator : NSObject
{
    long long _estimatedRSSI;
    long long _rssiThreshold;
}

+ (id)proximityEstimatorWithProximityInfo:(id)arg1;
@property(readonly, nonatomic) long long estimatedRSSI; // @synthesize estimatedRSSI=_estimatedRSSI;
- (BOOL)updateWithSFBLEDevice:(id)arg1;
- (id)initWithProximityInfo:(id)arg1;

@end

