//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>, SFService;

@interface SFRemoteAutoFillService : NSObject
{
    BOOL _activateCalled;
    BOOL _invalidateCalled;
    SFService *_service;
    int _serviceState;
    NSObject<OS_dispatch_queue> *_dispatchQueue;
    CDUnknownBlockType _showPINHandler;
}

@property(copy, nonatomic) CDUnknownBlockType showPINHandler; // @synthesize showPINHandler=_showPINHandler;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *dispatchQueue; // @synthesize dispatchQueue=_dispatchQueue;
- (void).cxx_destruct;
- (void)_receivedObject:(id)arg1 flags:(unsigned int)arg2;
- (void)_handleSessionStarted:(id)arg1;
- (int)_runServiceStart;
- (void)_run;
- (void)invalidate;
- (void)activate;
- (void)_cleanup;
- (void)dealloc;
- (id)init;

@end

