//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>, SFDevice, SFSession;

@interface SFRemoteAutoFillSession : NSObject
{
    BOOL _activateCalled;
    BOOL _invalidateCalled;
    int _pairState;
    SFSession *_session;
    int _sessionState;
    NSObject<OS_dispatch_queue> *_dispatchQueue;
    SFDevice *_peerDevice;
    CDUnknownBlockType _promptForPINHandler;
}

@property(copy, nonatomic) CDUnknownBlockType promptForPINHandler; // @synthesize promptForPINHandler=_promptForPINHandler;
@property(retain, nonatomic) SFDevice *peerDevice; // @synthesize peerDevice=_peerDevice;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *dispatchQueue; // @synthesize dispatchQueue=_dispatchQueue;
- (void).cxx_destruct;
- (void)_receivedObject:(id)arg1 flags:(unsigned int)arg2;
- (int)_runPair;
- (int)_runSessionStart;
- (void)_run;
- (void)_completedWithError:(id)arg1;
- (void)tryPIN:(id)arg1;
- (void)_cleanup;
- (void)invalidate;
- (void)activate;
- (void)dealloc;
- (id)init;

@end

