//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBCodable.h"

#import "INCodableAttributeAssociating.h"
#import "NSCopying.h"
#import "NSSecureCoding.h"
#import "_INPBIntentSupport.h"

@class INCodableAttribute, NSArray, NSString;

@interface _INPBIntentSupport : PBCodable <_INPBIntentSupport, NSSecureCoding, NSCopying, INCodableAttributeAssociating>
{
    struct _has;
    NSArray *_intentsRestrictedWhileLockeds;
    NSArray *_intentsSupporteds;
    INCodableAttribute *_associatedCodableAttribute;
}

+ (Class)intentsSupportedType;
+ (Class)intentsRestrictedWhileLockedType;
@property(copy, nonatomic) INCodableAttribute *associatedCodableAttribute; // @synthesize associatedCodableAttribute=_associatedCodableAttribute;
@property(copy, nonatomic) NSArray *intentsSupporteds; // @synthesize intentsSupporteds=_intentsSupporteds;
@property(copy, nonatomic) NSArray *intentsRestrictedWhileLockeds; // @synthesize intentsRestrictedWhileLockeds=_intentsRestrictedWhileLockeds;
- (void).cxx_destruct;
- (id)dictionaryRepresentation;
@property(readonly) unsigned long long hash;
- (BOOL)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (id)intentsSupportedAtIndex:(unsigned long long)arg1;
@property(readonly, nonatomic) unsigned long long intentsSupportedsCount;
- (void)addIntentsSupported:(id)arg1;
- (void)clearIntentsSupporteds;
- (id)intentsRestrictedWhileLockedAtIndex:(unsigned long long)arg1;
@property(readonly, nonatomic) unsigned long long intentsRestrictedWhileLockedsCount;
- (void)addIntentsRestrictedWhileLocked:(id)arg1;
- (void)clearIntentsRestrictedWhileLockeds;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

