//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBCodable.h"

#import "INCodableAttributeAssociating.h"
#import "NSCopying.h"
#import "NSSecureCoding.h"
#import "_INPBContactValue.h"

@class INCodableAttribute, NSArray, NSString, _INPBContactHandle, _INPBImageValue, _INPBValueMetadata;

@interface _INPBContactValue : PBCodable <_INPBContactValue, NSSecureCoding, NSCopying, INCodableAttributeAssociating>
{
    struct {
        unsigned int isMe:1;
        unsigned int suggestionType:1;
    } _has;
    BOOL _isMe;
    int _suggestionType;
    NSArray *_aliases;
    _INPBContactHandle *_contactHandle;
    NSString *_customIdentifier;
    NSString *_firstName;
    NSString *_fullName;
    NSString *_handle;
    _INPBImageValue *_image;
    NSString *_lastName;
    NSString *_nickName;
    NSString *_relationship;
    _INPBValueMetadata *_valueMetadata;
    INCodableAttribute *_associatedCodableAttribute;
}

+ (Class)aliasesType;
@property(copy, nonatomic) INCodableAttribute *associatedCodableAttribute; // @synthesize associatedCodableAttribute=_associatedCodableAttribute;
@property(retain, nonatomic) _INPBValueMetadata *valueMetadata; // @synthesize valueMetadata=_valueMetadata;
@property(nonatomic) int suggestionType; // @synthesize suggestionType=_suggestionType;
@property(copy, nonatomic) NSString *relationship; // @synthesize relationship=_relationship;
@property(copy, nonatomic) NSString *nickName; // @synthesize nickName=_nickName;
@property(copy, nonatomic) NSString *lastName; // @synthesize lastName=_lastName;
@property(nonatomic) BOOL isMe; // @synthesize isMe=_isMe;
@property(retain, nonatomic) _INPBImageValue *image; // @synthesize image=_image;
@property(copy, nonatomic) NSString *handle; // @synthesize handle=_handle;
@property(copy, nonatomic) NSString *fullName; // @synthesize fullName=_fullName;
@property(copy, nonatomic) NSString *firstName; // @synthesize firstName=_firstName;
@property(copy, nonatomic) NSString *customIdentifier; // @synthesize customIdentifier=_customIdentifier;
@property(retain, nonatomic) _INPBContactHandle *contactHandle; // @synthesize contactHandle=_contactHandle;
@property(copy, nonatomic) NSArray *aliases; // @synthesize aliases=_aliases;
- (void).cxx_destruct;
- (id)dictionaryRepresentation;
@property(readonly) unsigned long long hash;
- (BOOL)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
@property(readonly, nonatomic) BOOL hasValueMetadata;
- (int)StringAsSuggestionType:(id)arg1;
- (id)suggestionTypeAsString:(int)arg1;
@property(nonatomic) BOOL hasSuggestionType;
@property(readonly, nonatomic) BOOL hasRelationship;
@property(readonly, nonatomic) BOOL hasNickName;
@property(readonly, nonatomic) BOOL hasLastName;
@property(nonatomic) BOOL hasIsMe;
@property(readonly, nonatomic) BOOL hasImage;
@property(readonly, nonatomic) BOOL hasHandle;
@property(readonly, nonatomic) BOOL hasFullName;
@property(readonly, nonatomic) BOOL hasFirstName;
@property(readonly, nonatomic) BOOL hasCustomIdentifier;
@property(readonly, nonatomic) BOOL hasContactHandle;
- (id)aliasesAtIndex:(unsigned long long)arg1;
@property(readonly, nonatomic) unsigned long long aliasesCount;
- (void)addAliases:(id)arg1;
- (void)clearAliases;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

