//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBCodable.h"

#import "INCodableAttributeAssociating.h"
#import "NSCopying.h"
#import "NSSecureCoding.h"
#import "_INPBCustomCodableAttribute.h"

@class INCodableAttribute, NSString, _INPBValueMetadata;

@interface _INPBCustomCodableAttribute : PBCodable <_INPBCustomCodableAttribute, NSSecureCoding, NSCopying, INCodableAttributeAssociating>
{
    struct {
        unsigned int customCodableAttributeClass:1;
        unsigned int modifier:1;
        unsigned int runtimeTag:1;
        unsigned int scalarType:1;
    } _has;
    int _customCodableAttributeClass;
    int _modifier;
    int _runtimeTag;
    int _scalarType;
    _INPBCustomCodableAttribute *_associatedAttribute;
    NSString *_objectClassName;
    NSString *_propertyName;
    _INPBValueMetadata *_valueMetadata;
    INCodableAttribute *_associatedCodableAttribute;
}

@property(copy, nonatomic) INCodableAttribute *associatedCodableAttribute; // @synthesize associatedCodableAttribute=_associatedCodableAttribute;
@property(retain, nonatomic) _INPBValueMetadata *valueMetadata; // @synthesize valueMetadata=_valueMetadata;
@property(nonatomic) int scalarType; // @synthesize scalarType=_scalarType;
@property(nonatomic) int runtimeTag; // @synthesize runtimeTag=_runtimeTag;
@property(copy, nonatomic) NSString *propertyName; // @synthesize propertyName=_propertyName;
@property(copy, nonatomic) NSString *objectClassName; // @synthesize objectClassName=_objectClassName;
@property(nonatomic) int modifier; // @synthesize modifier=_modifier;
@property(nonatomic) int customCodableAttributeClass; // @synthesize customCodableAttributeClass=_customCodableAttributeClass;
@property(retain, nonatomic) _INPBCustomCodableAttribute *associatedAttribute; // @synthesize associatedAttribute=_associatedAttribute;
- (void).cxx_destruct;
- (id)dictionaryRepresentation;
@property(readonly) unsigned long long hash;
- (BOOL)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
@property(readonly, nonatomic) BOOL hasValueMetadata;
- (int)StringAsScalarType:(id)arg1;
- (id)scalarTypeAsString:(int)arg1;
@property(nonatomic) BOOL hasScalarType;
@property(nonatomic) BOOL hasRuntimeTag;
@property(readonly, nonatomic) BOOL hasPropertyName;
@property(readonly, nonatomic) BOOL hasObjectClassName;
- (int)StringAsModifier:(id)arg1;
- (id)modifierAsString:(int)arg1;
@property(nonatomic) BOOL hasModifier;
- (int)StringAsCustomCodableAttributeClass:(id)arg1;
- (id)customCodableAttributeClassAsString:(int)arg1;
@property(nonatomic) BOOL hasCustomCodableAttributeClass;
@property(readonly, nonatomic) BOOL hasAssociatedAttribute;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

