//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBCodable.h"

#import "INCodableAttributeAssociating.h"
#import "NSCopying.h"
#import "NSSecureCoding.h"
#import "_INPBDateTimeRangeList.h"

@class INCodableAttribute, NSArray, NSString, _INPBCondition;

@interface _INPBDateTimeRangeList : PBCodable <_INPBDateTimeRangeList, NSSecureCoding, NSCopying, INCodableAttributeAssociating>
{
    struct _has;
    _INPBCondition *_condition;
    NSArray *_dateRanges;
    INCodableAttribute *_associatedCodableAttribute;
}

+ (Class)dateRangeType;
@property(copy, nonatomic) INCodableAttribute *associatedCodableAttribute; // @synthesize associatedCodableAttribute=_associatedCodableAttribute;
@property(copy, nonatomic) NSArray *dateRanges; // @synthesize dateRanges=_dateRanges;
@property(retain, nonatomic) _INPBCondition *condition; // @synthesize condition=_condition;
- (void).cxx_destruct;
- (id)dictionaryRepresentation;
@property(readonly) unsigned long long hash;
- (BOOL)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (id)dateRangeAtIndex:(unsigned long long)arg1;
@property(readonly, nonatomic) unsigned long long dateRangesCount;
- (void)addDateRange:(id)arg1;
- (void)clearDateRanges;
@property(readonly, nonatomic) BOOL hasCondition;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

