//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, _INPBCustomCodableAttribute, _INPBValueMetadata;

@protocol _INPBCustomCodableAttribute <NSObject>
@property(readonly, nonatomic) BOOL hasValueMetadata;
@property(retain, nonatomic) _INPBValueMetadata *valueMetadata;
@property(nonatomic) BOOL hasScalarType;
@property(nonatomic) int scalarType;
@property(nonatomic) BOOL hasRuntimeTag;
@property(nonatomic) int runtimeTag;
@property(readonly, nonatomic) BOOL hasPropertyName;
@property(copy, nonatomic) NSString *propertyName;
@property(readonly, nonatomic) BOOL hasObjectClassName;
@property(copy, nonatomic) NSString *objectClassName;
@property(nonatomic) BOOL hasModifier;
@property(nonatomic) int modifier;
@property(nonatomic) BOOL hasCustomCodableAttributeClass;
@property(nonatomic) int customCodableAttributeClass;
@property(readonly, nonatomic) BOOL hasAssociatedAttribute;
@property(retain, nonatomic) _INPBCustomCodableAttribute *associatedAttribute;
- (int)StringAsScalarType:(NSString *)arg1;
- (NSString *)scalarTypeAsString:(int)arg1;
- (int)StringAsModifier:(NSString *)arg1;
- (NSString *)modifierAsString:(int)arg1;
- (int)StringAsCustomCodableAttributeClass:(NSString *)arg1;
- (NSString *)customCodableAttributeClassAsString:(int)arg1;
@end

