//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "INSpeakable.h"
#import "NSCopying.h"
#import "NSSecureCoding.h"
#import "_INSpeakable.h"

@class NSArray, NSString;

@interface INIdentifierString : NSObject <_INSpeakable, INSpeakable, NSCopying, NSSecureCoding>
{
    NSString *_string;
    NSString *_identifier;
}

+ (BOOL)supportsSecureCoding;
@property(readonly) NSString *identifier; // @synthesize identifier=_identifier;
@property(retain) NSString *string; // @synthesize string=_string;
- (void).cxx_destruct;
@property(readonly) NSArray *alternativeSpeakableMatches;
@property(readonly) NSString *pronunciationHint;
- (id)strings;
@property(readonly) NSArray *spokenPhrases;
@property(readonly) NSString *spokenPhrase;
@property(readonly) NSString *vocabularyIdentifier;
@property(readonly, copy) NSString *description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (BOOL)isEqual:(id)arg1;
@property(readonly) unsigned long long hash;
- (unsigned short)characterAtIndex:(unsigned long long)arg1;
- (unsigned long long)length;
- (id)_effectiveNSStringValue;
@property(copy, setter=_setIdentifier:) NSString *_identifier;
- (id)initWithString:(id)arg1;
- (id)initWithIdentifier:(id)arg1 string:(id)arg2;
- (id)_intents_localizedCopyForLanguage:(id)arg1;
- (id)_intents_readableDescriptionForLanguage:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

