//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Intents/INImage.h>

@class NSString;

@interface INRemoteImageProxy : INImage
{
    NSString *_storageServiceIdentifier;
    NSString *_proxyIdentifier;
}

+ (BOOL)supportsSecureCoding;
+ (void)requestProxyByStoringImage:(id)arg1 completion:(CDUnknownBlockType)arg2;
@property(copy, nonatomic, setter=_setProxyIdentifier:) NSString *_proxyIdentifier; // @synthesize _proxyIdentifier;
@property(copy, nonatomic, setter=_setStorageServiceIdentifier:) NSString *_storageServiceIdentifier; // @synthesize _storageServiceIdentifier;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)_dictionaryRepresentation;
- (void)_retrieveImageDataWithReply:(CDUnknownBlockType)arg1;
- (BOOL)isEqual:(id)arg1;
- (id)_copyWithSubclass:(Class)arg1;
@property(readonly, nonatomic) BOOL isValid;
- (void)purgeStoredImageWithCompletion:(CDUnknownBlockType)arg1;
- (id)_URLRepresentation;
- (id)_initWithURLRepresentation:(id)arg1;

@end

