//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CSAssetControllerDelegate.h"
#import "CSLanguageCodeUpdateMonitorDelegate.h"
#import "CSSpeechEndpointAssetMetaUpdateMonitorDelegate.h"
#import "CSVoiceTriggerAssetMetaUpdateMonitorDelegate.h"

@class CSPolicy, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString;

@interface CSAssetManager : NSObject <CSVoiceTriggerAssetMetaUpdateMonitorDelegate, CSSpeechEndpointAssetMetaUpdateMonitorDelegate, CSAssetControllerDelegate, CSLanguageCodeUpdateMonitorDelegate>
{
    NSObject<OS_dispatch_queue> *_queue;
    CSPolicy *_enablePolicy;
    NSString *_currentLanguageCode;
    NSMutableDictionary *_observers;
    BOOL _daemonRunningMode;
}

+ (id)sharedManager;
- (void).cxx_destruct;
- (void)CSAssetController:(id)arg1 didDownloadNewAssetForType:(unsigned long long)arg2;
- (void)CSSpeechEndpointAssetMetaUpdateMonitor:(id)arg1 didReceiveNewSpeechEndpointAssetMetaData:(BOOL)arg2;
- (void)CSVoiceTriggerAssetMetaUpdateMonitor:(id)arg1 didReceiveNewVoiceTriggerAssetMetaData:(BOOL)arg2;
- (void)removeObserver:(id)arg1 forAssetType:(unsigned long long)arg2;
- (void)addObserver:(id)arg1 forAssetType:(unsigned long long)arg2;
- (void)CSLanguageCodeUpdateMonitor:(id)arg1 didReceiveLanguageCodeChanged:(id)arg2;
@property(readonly, nonatomic) NSString *currentLanguageCode;
- (BOOL)_canFetchRemoteAsset:(unsigned long long)arg1;
- (void)_fetchRemoteMetaData;
- (void)installedAssetOfType:(unsigned long long)arg1 language:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)installedAssetOfType:(unsigned long long)arg1 language:(id)arg2;
- (void)assetOfType:(unsigned long long)arg1 language:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)assetOfType:(unsigned long long)arg1 language:(id)arg2;
- (void)installedAssetForCurrentLanguageOfType:(unsigned long long)arg1 completion:(CDUnknownBlockType)arg2;
- (id)installedAssetForCurrentLanguageOfType:(unsigned long long)arg1;
- (void)assetForCurrentLanguageOfType:(unsigned long long)arg1 completion:(CDUnknownBlockType)arg2;
- (id)assetForCurrentLanguageOfType:(unsigned long long)arg1;
- (void)setDaemonRunningMode:(BOOL)arg1;
- (id)initWithDaemonMode:(BOOL)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

