//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CSSpIdProcessorDelegate.h"
#import "CSSpIdSpeakerRecognizer.h"

@class CSSpIdContext, CSSpIdProcessor, NSDictionary, NSObject<OS_dispatch_queue>, NSString;

@interface CSSpIdVTSpeakerRecognizer : NSObject <CSSpIdProcessorDelegate, CSSpIdSpeakerRecognizer>
{
    BOOL _processingEnded;
    CSSpIdContext *_spIdCtx;
    NSString *_invocationStyleStr;
    id <CSSpIdSpeakerRecognizerDelegate> _delegate;
    unsigned long long _extraSamplesAtStart;
    unsigned long long _tdEndInSampleCount;
    unsigned long long _totalNumSamplesReceived;
    CSSpIdProcessor *_tdtiSpIdProcessor;
    id <CSAudioFileWriter> _dbgTdTiUttLogger;
    unsigned long long _tdtiEndInSampleCount;
    unsigned long long _numTdTiSamplesProcessed;
    unsigned long long _myriadResult;
    NSDictionary *_lastSpeakerIdInfo;
    NSObject<OS_dispatch_queue> *_queue;
}

- (void)setCVTTriggerPhraseDetected;
- (void)processMyriadDecision:(unsigned long long)arg1;
- (void)recordingStoppedForReason:(long long)arg1;
- (void)_endAudioProcessing;
- (void)_processAudioData:(id)arg1 numSamples:(unsigned long long)arg2;
- (void)processAudioChunk:(id)arg1;
- (void)dealloc;
- (id)initWithContext:(id)arg1 delegate:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

