//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CSSpIdProcessorDelegate.h"
#import "CSSpIdSpeakerRecognizer.h"

@class CSSpIdContext, CSSpIdProcessor, NSDictionary, NSObject<OS_dispatch_queue>, NSString;

@interface CSSpIdTIOnlySpeakerRecognizer : NSObject <CSSpIdProcessorDelegate, CSSpIdSpeakerRecognizer>
{
    BOOL _processingEnded;
    CSSpIdContext *_spIdCtx;
    NSString *_invocationStyle;
    id <CSSpIdSpeakerRecognizerDelegate> _delegate;
    CSSpIdProcessor *_tiSpIdProcessor;
    unsigned long long _tiEndInSampleCount;
    unsigned long long _numTISamplesProcessed;
    unsigned long long _myriadResult;
    NSDictionary *_lastSpeakerIdInfo;
    id <CSAudioFileWriter> _dbgTiUttLogger;
    NSObject<OS_dispatch_queue> *_queue;
}

- (void)setCVTTriggerPhraseDetected;
- (void)processMyriadDecision:(unsigned long long)arg1;
- (void)_endAudioProcessing;
- (void)recordingStoppedForReason:(long long)arg1;
- (void)_processAudioData:(id)arg1 numSamples:(unsigned long long)arg2;
- (void)processAudioChunk:(id)arg1;
- (void)dealloc;
- (id)initWithContext:(id)arg1 delegate:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

