//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableDictionary, NSMutableIndexSet, NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_source>;

@interface PPQuickTypeEventCache : NSObject
{
    CDUnknownBlockType _backfiller;
    NSArray *_cachedEvents;
    NSMutableIndexSet *_cachedRanges;
    unsigned long long _extraSecondsToBackfill;
    NSMutableDictionary *_cachedEventHighlights;
    NSObject<OS_dispatch_queue> *_queue;
    NSObject<OS_dispatch_source> *_memoryPressureSource;
    unsigned long long _memoryPressureStatus;
}

@property(nonatomic) unsigned long long extraSecondsToBackfill; // @synthesize extraSecondsToBackfill=_extraSecondsToBackfill;
- (void).cxx_destruct;
- (id)cachedEventHighlightForEKEvent:(id)arg1 rankingOptions:(int)arg2;
- (void)setEventHighlight:(id)arg1;
- (void)evictAllExceptRangesInIndexSet:(id)arg1;
- (void)evictEvents:(id)arg1;
- (void)evictAllExceptRange:(struct _NSRange)arg1;
- (void)removeAllObjects;
- (id)objectForRange:(struct _NSRange)arg1;
- (void)_handleMemoryPressureStatus;
- (id)initWithBackfiller:(CDUnknownBlockType)arg1;

@end

