//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, SKDisk;

@interface OSIDebuggerTool : NSObject
{
    SKDisk *_target;
    NSString *_opToFail;
    double _failAtProgress;
}

@property double failAtProgress; // @synthesize failAtProgress=_failAtProgress;
@property(retain) NSString *opToFail; // @synthesize opToFail=_opToFail;
@property(retain) SKDisk *target; // @synthesize target=_target;
- (void).cxx_destruct;
- (void)updateStatusWithQueueElement:(id)arg1 progress:(double)arg2;
- (BOOL)loadDebuggerPropertyList;
- (id)initWithTarget:(id)arg1;

@end

