//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "USSXPCEncodable.h"

@class NSString;

@interface USSSceneActiveRequest : NSObject <USSXPCEncodable>
{
    BOOL _isOnActiveSpace;
    BOOL _isVisible;
    BOOL _isAppHidden;
    NSString *_identifier;
}

+ (id)sceneActiveRequestForScene:(id)arg1 isOnActiveSpace:(BOOL)arg2 isVisible:(BOOL)arg3 isAppHidden:(BOOL)arg4;
@property(nonatomic) BOOL isAppHidden; // @synthesize isAppHidden=_isAppHidden;
@property(nonatomic) BOOL isVisible; // @synthesize isVisible=_isVisible;
@property(nonatomic) BOOL isOnActiveSpace; // @synthesize isOnActiveSpace=_isOnActiveSpace;
@property(retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (void)encodeWithXPCDictionary:(id)arg1;
- (id)initWithXPCDictionary:(id)arg1;
- (id)initCommon;

@end

