//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSColor.h"

@interface NSColor (CalClassAdditions)
+ (id)_findColorForName:(id)arg1;
+ (id)_getAlternateNameForColorName:(id)arg1 inAppearance:(id)arg2;
+ (id)cal_dynamicColorNamed:(id)arg1 forView:(id)arg2;
+ (id)cal_dynamicColorNamed:(id)arg1 forAppearance:(id)arg2;
+ (id)cal_dynamicColorNamed:(id)arg1;
+ (id)_adjustColor:(id)arg1 withCurrentLuminance:(double)arg2 toLuminance:(double)arg3 blendFraction:(double)arg4;
@property(readonly) double cal_luminance;
@property(readonly) BOOL cal_isLightColor;
@property(readonly) BOOL cal_isDarkColor;
- (id)cal_dynamicColorForView:(id)arg1;
- (id)cal_dynamicColorForAppearance:(id)arg1;
- (id)cal_adjustedToAtMostLuminance:(double)arg1;
- (id)cal_adjustedToAtLeastLuminance:(double)arg1;
@end

