//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class PDAssertion;

@interface PDAssertionRequest : NSObject
{
    PDAssertion *_assertion;
    CDUnknownBlockType _resultHandler;
}

@property(copy, nonatomic) CDUnknownBlockType resultHandler; // @synthesize resultHandler=_resultHandler;
@property(retain, nonatomic) PDAssertion *assertion; // @synthesize assertion=_assertion;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (id)initWithAssertion:(id)arg1 resultHandler:(CDUnknownBlockType)arg2;

@end

