//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PassKitCore/PKPaymentWebServiceRequest.h>

@class NSString;

@interface PKPaymentServiceProviderPurchaseRequest : PKPaymentWebServiceRequest
{
    NSString *_purchaseIdentifier;
    NSString *_purchaseState;
    NSString *_serviceProviderIdentifier;
}

@property(copy, nonatomic) NSString *serviceProviderIdentifier; // @synthesize serviceProviderIdentifier=_serviceProviderIdentifier;
@property(copy, nonatomic) NSString *purchaseState; // @synthesize purchaseState=_purchaseState;
@property(copy, nonatomic) NSString *purchaseIdentifier; // @synthesize purchaseIdentifier=_purchaseIdentifier;
- (void).cxx_destruct;
- (id)_urlRequestWithServiceURL:(id)arg1 account:(id)arg2;
- (id)initWithPurchaseIdentifier:(id)arg1 purchaseState:(id)arg2 serviceProviderIdentifier:(id)arg3;
- (id)initWithPurchaseIdentifier:(id)arg1;

@end

