//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "RPCompanionLinkXPCServerInterface.h"

@class NSObject<OS_dispatch_queue>, NSXPCConnection, RPCompanionLinkClient, RPCompanionLinkDaemon;

__attribute__((visibility("hidden")))
@interface RPCompanionLinkXPCConnection : NSObject <RPCompanionLinkXPCServerInterface>
{
    RPCompanionLinkClient *_client;
    RPCompanionLinkDaemon *_daemon;
    NSObject<OS_dispatch_queue> *_dispatchQueue;
    BOOL _entitled;
    BOOL _localDeviceUpdated;
    struct NSMutableDictionary *_registeredEvents;
    struct NSMutableDictionary *_registeredRequests;
    NSXPCConnection *_xpcCnx;
    unsigned int _xpcID;
}

@property(retain, nonatomic) NSObject<OS_dispatch_queue> *dispatchQueue; // @synthesize dispatchQueue=_dispatchQueue;
- (void).cxx_destruct;
- (void)companionLinkSendRequestID:(id)arg1 request:(id)arg2 destinationID:(id)arg3 options:(id)arg4 responseHandler:(CDUnknownBlockType)arg5;
- (void)companionLinkDeregisterRequestID:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)companionLinkRegisterRequestID:(id)arg1 options:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)companionLinkSendEventID:(id)arg1 event:(id)arg2 destinationID:(id)arg3 options:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)companionLinkDeregisterEventID:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)companionLinkRegisterEventID:(id)arg1 options:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)companionLinkActivateClient:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)companionLinkInvalidateAssertion:(id)arg1;
- (void)companionLinkActivateAssertion:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (BOOL)_entitledAndReturnError:(id *)arg1;
- (void)connectionInvalidated;
- (id)initWithDaemon:(id)arg1 xpcCnx:(id)arg2;

@end

