//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface RPRangingMeasurement : NSObject
{
    double _angle;
    double _distance;
}

@property(nonatomic) double distance; // @synthesize distance=_distance;
@property(nonatomic) double angle; // @synthesize angle=_angle;

@end

