//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface PARFeedbackFilterController : NSObject
{
    struct __CFSet *_identifierHashes;
}

- (void)filterResult:(id)arg1;
- (void)filterCodable:(id)arg1;
- (void)resetFilter;
- (id)init;

@end

