//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSButton.h"

@class NSImage, NSVisualEffectView;

@interface LUI2VisualEffectButton : NSButton
{
    NSVisualEffectView *_backgroundView;
}

+ (void)initialize;
@property(retain) NSVisualEffectView *backgroundView; // @synthesize backgroundView=_backgroundView;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(retain) NSImage *image;
- (void)_setupVisualEffectButton;

@end

