//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSButton.h"

@class NSDictionary, NSImageView, NSString, NSTextField, NSVisualEffectView;

@interface LUI2GlyphButton : NSButton
{
    NSVisualEffectView *_glyphBackgroundView;
    NSImageView *_glyphView;
    NSTextField *_titleView;
    NSDictionary *_images;
}

+ (void)initialize;
+ (id)buttonWithTitle:(id)arg1 imageIdentifier:(id)arg2 target:(id)arg3 action:(SEL)arg4;
+ (id)buttonWithIdentifier:(id)arg1 target:(id)arg2 action:(SEL)arg3;
@property(retain) NSDictionary *images; // @synthesize images=_images;
@property(retain) NSTextField *titleView; // @synthesize titleView=_titleView;
@property(retain) NSImageView *glyphView; // @synthesize glyphView=_glyphView;
@property(retain) NSVisualEffectView *glyphBackgroundView; // @synthesize glyphBackgroundView=_glyphBackgroundView;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(copy) NSString *title;
- (void)setImageIdentifier:(id)arg1;
- (void)setEnabled:(BOOL)arg1;
- (BOOL)resignFirstResponder;
- (void)mouseUp:(id)arg1;
- (void)setHighlighted:(BOOL)arg1;
- (BOOL)becomeFirstResponder;
- (id)accessibilityChildren;
- (id)accessibilityLabel;
- (void)_updateTitle:(BOOL)arg1 highlighted:(BOOL)arg2;
- (void)_updateImages:(BOOL)arg1 highlighted:(BOOL)arg2;
- (void)_setupButtonView;
- (id)_maskImageOfSize:(struct CGSize)arg1;
- (id)_imagesForIdentifier:(id)arg1;
- (void)_glyphViewPressed:(id)arg1;
- (id)_appearance;

@end

